#include <cstdio>

using namespace std;

char a[256];

int main() {
a[' '] = ' ';
a['y'] = 'a';
a['e'] = 'o';
a['q'] = 'z';
a['e'] = 'o';
a['j'] = 'u';
a['p'] = 'r';
a['m'] = 'l';
a['y'] = 'a';
a['s'] = 'n';
a['l'] = 'g';
a['j'] = 'u';
a['y'] = 'a';
a['l'] = 'g';
a['c'] = 'e';
a['k'] = 'i';
a['d'] = 's';
a['k'] = 'i';
a['x'] = 'm';
a['v'] = 'p';
a['e'] = 'o';
a['d'] = 's';
a['d'] = 's';
a['k'] = 'i';
a['n'] = 'b';
a['m'] = 'l';
a['c'] = 'e';
a['r'] = 't';
a['e'] = 'o';
a['j'] = 'u';
a['s'] = 'n';
a['i'] = 'd';
a['c'] = 'e';
a['p'] = 'r';
a['d'] = 's';
a['r'] = 't';
a['y'] = 'a';
a['s'] = 'n';
a['i'] = 'd';
a['r'] = 't';
a['b'] = 'h';
a['c'] = 'e';
a['p'] = 'r';
a['c'] = 'e';
a['y'] = 'a';
a['p'] = 'r';
a['c'] = 'e';
a['r'] = 't';
a['t'] = 'w';
a['c'] = 'e';
a['s'] = 'n';
a['r'] = 't';
a['a'] = 'y';
a['d'] = 's';
a['k'] = 'i';
a['h'] = 'x';
a['w'] = 'f';
a['y'] = 'a';
a['f'] = 'c';
a['r'] = 't';
a['e'] = 'o';
a['p'] = 'r';
a['k'] = 'i';
a['y'] = 'a';
a['m'] = 'l';
a['v'] = 'p';
a['e'] = 'o';
a['d'] = 's';
a['d'] = 's';
a['k'] = 'i';
a['n'] = 'b';
a['k'] = 'i';
a['m'] = 'l';
a['k'] = 'i';
a['r'] = 't';
a['k'] = 'i';
a['c'] = 'e';
a['d'] = 's';
a['d'] = 's';
a['e'] = 'o';
a['k'] = 'i';
a['r'] = 't';
a['k'] = 'i';
a['d'] = 's';
a['e'] = 'o';
a['o'] = 'k';
a['y'] = 'a';
a['a'] = 'y';
a['k'] = 'i';
a['w'] = 'f';
a['a'] = 'y';
a['e'] = 'o';
a['j'] = 'u';
a['t'] = 'w';
a['y'] = 'a';
a['s'] = 'n';
a['r'] = 't';
a['r'] = 't';
a['e'] = 'o';
a['u'] = 'j';
a['j'] = 'u';
a['d'] = 's';
a['r'] = 't';
a['l'] = 'g';
a['k'] = 'i';
a['g'] = 'v';
a['c'] = 'e';
a['j'] = 'u';
a['v'] = 'p';
a['z'] = 'q';
	int t;
	scanf("%i", &t);
	char c;
	scanf("%c", &c);
	for(int i = 0; i < t; i++) {
		printf("Case #%i: ", i + 1);
		while(scanf("%c", &c) == 1 && c != '\n') printf("%c", a[c]);
		printf("\n");
	}
}

