#include <stdio.h>
#include <conio.h>
#include <string.h>
#include<stdlib.h>
int main()
{
     int i,j,l,t;
     char s[101],res[30][101],c,n[2];
     freopen("A-small-attempt1.in","rt",stdin);
     freopen("res1.txt","wt",stdout);
 gets(n);
 t=atoi(n);
 for(i=0;i<t;i++)
 {
                 gets(s);
                l=strlen(s);
                for(j=0;j<l;j++)
                {
                  c=s[j];
                  switch(c)
                  {
                           case('y'):
                                     {
                                     res[i][j]='a'; 
                                     break;      
                                     }
                           case('n'):
                                     {
                                     res[i][j]='b'; 
                                     break;      
                                     } 
                           case('f'):
                                     {
                                     res[i][j]='c';       
                                     break;
                                     } 
                           case('i'):
                                     {
                                     res[i][j]='d';       
                                     break;
                                     } 
                           case('c'):
                                     {
                                     res[i][j]='e';       
                                     break;
                                     } 
                           case('w'):
                                     {
                                     res[i][j]='f';       
                                     break;
                                     } 
                           case('l'):
                                     {
                                     res[i][j]='g';       
                                     break;
                                     }
                           case('b'):
                                     {
                                     res[i][j]='h'; 
                                     break;
                                     }  
                           case('k'):
                                     {
                                     res[i][j]='i';       
                                     break;
                                     }
                           case('u'):
                                     {
                                     res[i][j]='j';       
                                     break;
                                     }
                          case('o'):
                                     {
                                     res[i][j]='k';       
                                     break;
                                     }
                          case('m'):
                                     {
                                     res[i][j]='l';       
                                     break;
                                     } 
                          case('x'):
                                     {
                                     res[i][j]='m';       
                                     break;
                                     }
                          case('s'):
                                     {
                                     res[i][j]='n';       
                                     break;
                                     }     
                          case('e'):
                                     {
                                     res[i][j]='o';       
                                     break;
                                     }
                          case('v'):
                                     {
                                     res[i][j]='p';       
                                     break;
                                     }
                          case('z'):
                                     {
                                     res[i][j]='q';       
                                     break;
                                     }
                          case('p'):
                                     {
                                     res[i][j]='r';       
                                     break;
                                     }
                          case('d'):
                                     {
                                     res[i][j]='s';       
                                     break;
                                     }
                          case('r'):
                                     {
                                     res[i][j]='t';       
                                     break;
                                     }
                          case('j'):
                                     {
                                     res[i][j]='u';       
                                     break;
                                     }
                          case('g'):
                                     {
                                     res[i][j]='v';       
                                     break;
                                     } 
                          case('t'):
                                     {
                                     res[i][j]='w';       
                                     break;
                                     }
                          case('h'):
                                     {
                                     res[i][j]='x';       
                                     break;
                                     }
                          case('a'):
                                     {
                                     res[i][j]='y';       
                                     break;
                                     }
                          case('q'):
                                     {
                                     res[i][j]='z';       
                                     break;
                                     }
                          default:
                                  {
                                   res[i][j]=s[j];   
                                  }                           
                  }              
                }
                res[i][l]=NULL;
}
                for(i=0;i<t;i++)
                {
                                printf("Case #%d: ",i+1);
                                puts(res[i]);
                }
 return(0);
}
