/*******************************************************************************
 * jason.molenda@gmail.com
 ******************************************************************************/

#include <stdlib.h>
#include <stdio.h>
#include <conio.h>
#include <stdarg.h>
#include <string.h>


/*******************************************************************************
 *
 ******************************************************************************/

typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;


typedef signed char int8_t;
typedef signed short int16_t;
typedef signed int int32_t;


/*******************************************************************************
 *
 ******************************************************************************/

#define NO_BITS 0x00
#define BIT0    0x01
#define BIT1    0x02
#define BIT2    0x04
#define BIT3    0x08
#define BIT4    0x10
#define BIT5    0x20
#define BIT6    0x40
#define BIT7    0x80
#define BIT8    0x0100
#define BIT9    0x0200
#define BIT10   0x0400
#define BIT11   0x0800
#define BIT12   0x1000
#define BIT13   0x2000
#define BIT14   0x4000
#define BIT15   0x8000
#define BIT16   0x010000
#define BIT17   0x020000
#define BIT18   0x040000
#define BIT19   0x080000
#define BIT20   0x100000
#define BIT21   0x200000
#define BIT22   0x400000
#define BIT23   0x800000
#define BIT24   0x01000000
#define BIT25   0x02000000
#define BIT26   0x04000000
#define BIT27   0x08000000
#define BIT28   0x10000000
#define BIT29   0x20000000
#define BIT30   0x40000000
#define BIT31   0x80000000

/*******************************************************************************
 * used to eliminate the warnings/errors generated by the compiler when
 * there are unused arguments in a function.
 ******************************************************************************/
#define UNUSED_ARG(a)         do {/* nothing */} while (&a == 0)

/*******************************************************************************
 *
 ******************************************************************************/

#define LOG_FILE_NAME                        "log.txt"


/*******************************************************************************
 * globals
 ******************************************************************************/

FILE* log_file;

/*******************************************************************************
 *
 ******************************************************************************/

void dual_printf(char *fmt, ...);
int main(int argc, char * argv[]);
int real_main(int argc, char * argv[]);


/*******************************************************************************
 * prints to a file and to Std Out
 ******************************************************************************/
void dual_printf(char *fmt, ...)
{
   va_list ap;

   // do printf
   va_start(ap, fmt);
   vprintf(fmt, ap);  // write to stdout
   va_end(ap);

   // do file output
   va_start(ap, fmt);
   vfprintf(log_file, fmt, ap);  // write to log file
   va_end(ap);

   fflush(log_file);
}


/*******************************************************************************
 *
 ******************************************************************************/
int main(int argc, char * argv[])
{
   log_file = fopen(LOG_FILE_NAME, "wt");
   printf("Saving results to '%s'...\n", LOG_FILE_NAME);

   if (log_file == NULL)
   {
      printf("error: opening file '%s'\n", LOG_FILE_NAME);
      return 0;
   }


   real_main(argc, argv);


   fclose(log_file);


   printf("Done!\n");
   printf("Press any key to continue . . . ");
   getch();


   return 0;
}


/*******************************************************************************
 *
 ******************************************************************************/
int real_main(int argc, char * argv[])
{
   UNUSED_ARG(argc);
   UNUSED_ARG(argv);


   char alphabet[26];
   char found[26];

   memset(&found, 0, sizeof(found));

   alphabet['z' - 'a'] = 'q';
   alphabet['q' - 'a'] = 'z';

   char string1[] = "ejp mysljylc kd kxveddknmc re jsicpdrysi rbcpc ypc rtcsra dkh wyfrepkym veddknkmkrkcd de kr kd eoya kw aej tysr re ujdr lkgc jv";
   char string2[] = "our language is impossible to understand there are twenty six factorial possibilities so it is okay if you want to just give up";

   for (uint32_t xx = 0; xx < strlen(string1); xx++)
   {
      if (string1[xx] != ' ')
      {
         char one_char;
         one_char = char (string1[xx] - 'a');
         found[one_char] = 1;
         alphabet[one_char] = string2[xx];
      }
   }

   for (uint32_t xx = 0; xx < sizeof(alphabet); xx++)
   {
      //printf("%c -> %c\n", xx + 'a', alphabet[xx], found[xx]);
   }

   FILE* input_file;

   input_file = fopen("input.txt", "rt");
   if (input_file == NULL)
   {
      return 0;
   }

   uint32_t num_test_cases;
   fscanf(input_file, "%d\n", &num_test_cases);

   for (uint32_t test_case_num = 0; test_case_num < num_test_cases; test_case_num++)
   {
      char some_string[110];

      fscanf(input_file, "%[^\n]\n", &some_string[0]);
      //dual_printf("'%s'\n", some_string);

      dual_printf("Case #%d: ", test_case_num + 1);
      for (uint32_t xx = 0; xx < strlen(some_string); xx++)
      {
         if (some_string[xx] != ' ')
         {
            dual_printf("%c", alphabet[some_string[xx] - 'a']);
         }
         else
         {
            dual_printf(" ");
         }
      }
      dual_printf("\n");
   }


   fclose(input_file);


   return 0;
}


/*******************************************************************************
 * END OF FILE
 ******************************************************************************/


