{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# imports\n",
    "import numpy as np # http://www.numpy.org/\n",
    "import math # https://docs.python.org/2/library/math.html\n",
    "import itertools as it # https://docs.python.org/2/library/itertools.html"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "basepath = '/home/epg/halde/codejam/2016/1C/'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "#testset = 'A-sample'\n",
    "#testset = 'A-small-attempt0'\n",
    "testset = 'A-large'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'\n",
    "def do_solve(N, P):\n",
    "    out = []\n",
    "    \n",
    "    while sum(P) > 0:\n",
    "        # get first group with max. members\n",
    "        ind_max = P.index(max(P))\n",
    "        group = letters[ind_max]\n",
    "        P[ind_max] -= 1\n",
    "        \n",
    "        # get next group with max. members\n",
    "        ind_max = P.index(max(P))\n",
    "        # check if there's a majority\n",
    "        if P[ind_max] > sum(P)/2:\n",
    "            group += letters[ind_max]\n",
    "            P[ind_max] -= 1\n",
    "        \n",
    "        out.append(group)\n",
    "    return ' '.join(out)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Case #1: AB AB\n",
      "Case #2: A A B C A BC\n",
      "Case #3: C A BC\n",
      "Case #4: B A B A BC\n",
      "Case #5: E E E E E E E E E E E E B E B E B E B E B E B E B E B E B E B C E B C E B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C DE\n",
      "Case #6: C C C C C C C C C C C C C C C C C C C C C C C A C A C D A C D A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E I N A B C D E I N A B C D E I N O A B C D E I N O A B C D E I M N O S A B C D E I M N O S Y Z A B C D E H I M N O S W Y Z A B C D E H I M N O S W Y Z A B C D E H I J M N O S W Y Z A B C D E H I J M N O S W Y Z A B C D E H I J L M N O Q S V W Y Z A B C D E H I J K L M N O Q S V W Y Z A B C D E H I J K L M N O Q S U V W Y Z A B C D E H I J K L M N O P Q S U V W Y Z A B C D E F G H I J K L M N O P Q S U V W Y Z A B C D E F G H I J K L M N O P Q R S T U V W Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #7: A BC\n",
      "Case #8: X X X X K X K X K X K X K X K X K U X K U X K U X G K P U V X B G K P T U V X B G K L P T U V X B F G I K L O P R T U V X B F G I K L O P R T U V X B E F G I K L O P R T U V X Y B E F G I J K L O P R T U V X Y B C E F G I J K L O P R T U V X Y B C E F G H I J K L O P R S T U V X Y B C E F G H I J K L M O P R S T U V X Y B C E F G H I J K L M O P R S T U V W X Y B C E F G H I J K L M O P R S T U V W X Y B C E F G H I J K L M O P Q R S T U V W X Y A B C E F G H I J K L M O P Q R S T U V W X Y A B C D E F G H I J K L M O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #9: A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #10: K K K K N K N K N S G K N S G K N S G K N S G K N R S D G K N R S D G K N R S D G H K N Q R S D G H K N Q R S A D F G H I J K N P Q R S A D F G H I J K M N P Q R S T A C D F G H I J K M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A C D F G H I J K L M N P Q R S T A B C D F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R S T A B C D E F G H I J K L M N O P Q R ST\n",
      "Case #11: A A C A C A BC\n",
      "Case #12: E E E E E E E E E E E E E E E C E C E C E H C E H C E H C E H C E H C E H I C E H I C E H I C E F H I C E F H I B C E F G H I B C E F G H I B C E F G H I B C E F G H I B C E F G H I B C D E F G H I B C D E F G H I B C D E F G H I B C D E F G H I B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G H I A B C D E F G HI\n",
      "Case #13: G G G G G G G G G G G G G G A B C D E F G H I J K L M N OP\n",
      "Case #14: D D D D D D D D D D A D A D A D A D E A D E A D E A D E A D E A D E A D E A D E A D E A D E A C D E A C D E A C D E A C D E A C D E A C D E A C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C D E A B C DE\n",
      "Case #15: A A A A A C A C A C A C A C A C A C A C A C A C A C A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B CD\n",
      "Case #16: B B B B B B B B B B B B B B B B B B B B B B B C B C B C B C B C B C B C B C B C B C B C B C B C B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D X A B C D X A B C D X A B C D X A B C D E X A B C D E I U X A B C D E I N U W X A B C D E G I N Q U W X A B C D E G I N Q U W X A B C D E G I N Q U W X A B C D E G H I J N O Q U W X Y A B C D E G H I J N O Q R T U V W X Y A B C D E F G H I J N O Q R T U V W X Y A B C D E F G H I J K M N O Q R T U V W X Y A B C D E F G H I J K M N O P Q R T U V W X Y A B C D E F G H I J K M N O P Q R T U V W X Y A B C D E F G H I J K M N O P Q R T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #17: G V G N U V B G N U V B G N T U V B C G L M N T U V B C G J L M N O S T U V X B C G H J L M N O R S T U V X B C G H J L M N O Q R S T U V X B C G H J L M N O Q R S T U V X Y B C F G H I J L M N O Q R S T U V X Y Z B C F G H I J L M N O Q R S T U V X Y Z B C F G H I J L M N O P Q R S T U V X Y Z B C D F G H I J L M N O P Q R S T U V X Y Z A B C D F G H I J L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #18: F F F F F F F F F F F F F W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W F J W E F J W E F J W E F J M W E F J M W C E F J M W C E F J M W C E F J M U W Y C E F I J K M N O U W Y A C E F I J K L M N O P S U W Y A C E F H I J K L M N O P Q S U W Y A C D E F H I J K L M N O P Q S U W Y A C D E F H I J K L M N O P Q S U V W Y A C D E F G H I J K L M N O P Q S U V W Y Z A C D E F G H I J K L M N O P Q S U V W Y Z A C D E F G H I J K L M N O P Q S U V W Y Z A C D E F G H I J K L M N O P Q S U V W Y Z A B C D E F G H I J K L M N O P Q R S U V W Y Z A B C D E F G H I J K L M N O P Q R S U V W Y Z A B C D E F G H I J K L M N O P Q R S T U V W Y Z A B C D E F G H I J K L M N O P Q R S T U V W Y Z A B C D E F G H I J K L M N O P Q R S T U V W Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #19: J J J J J B J B J Y B J Y B J Y B J Y B J Y B J S Y B J S Y B J S Y B J S Y B J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J S Y B H J M R S Y B H J M R S Y B H J M R S Y B H J M R S Y B H J M R S Y B H J M R S Y B H J M Q R S Y B D H J M Q R S Y B D H J M Q R S Y B D H J L M Q R S V Y B D H J L M Q R S U V Y B D E H J L M Q R S U V Y B D E H J L M O P Q R S T U V Y B D E G H J K L M N O P Q R S T U V Y B D E G H J K L M N O P Q R S T U V X Y B D E F G H I J K L M N O P Q R S T U V W X Y B D E F G H I J K L M N O P Q R S T U V W X Y Z A B D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #20: C A C A B C A BC\n",
      "Case #21: S S S S S G S G S G S C G S C G J S C G J S C G J S C G J S C G J S C F G J L M N Q S C F G J L M N Q S C F G J L M N Q S B C F G J L M N Q S B C F G I J L M N Q S B C F G I J K L M N P Q S B C F G H I J K L M N P Q S B C F G H I J K L M N P Q S B C F G H I J K L M N P Q S A B C F G H I J K L M N P Q R S A B C F G H I J K L M N P Q R S A B C F G H I J K L M N P Q R S A B C D F G H I J K L M N O P Q R S A B C D F G H I J K L M N O P Q R S A B C D F G H I J K L M N O P Q R S A B C D F G H I J K L M N O P Q R S A B C D F G H I J K L M N O P Q R S A B C D F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q R S A B C D E F G H I J K L M N O P Q RS\n",
      "Case #22: A B A B C A BC\n",
      "Case #23: H H H N H N H N R C H L N R Z B C H L N R Z B C H L N R Z B C H L N R Z B C H L N R V Z B C H I L N R V Z B C E H I L N O R V Z B C D E F H I L N O R S V X Z B C D E F H I K L N O P R S V X Z B C D E F H I K L N O P R S V X Y Z B C D E F H I K L N O P R S V X Y Z B C D E F H I J K L M N O P R S T V W X Y Z B C D E F H I J K L M N O P R S T V W X Y Z B C D E F H I J K L M N O P R S T U V W X Y Z B C D E F H I J K L M N O P Q R S T U V W X Y Z A B C D E F H I J K L M N O P Q R S T U V W X Y Z A B C D E F H I J K L M N O P Q R S T U V W X Y Z A B C D E F H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #24: U F U F S U F S U F S U D F S U Z D F S U Z D F S U Z D F S U W Z C D F G H S U W Z C D F G H P Q S U W X Z C D F G H P Q S U W X Z C D F G H P Q S U V W X Z C D E F G H P Q S U V W X Y Z C D E F G H P Q S U V W X Y Z C D E F G H J K P Q S U V W X Y Z C D E F G H J K P Q S U V W X Y Z B C D E F G H J K L P Q S U V W X Y Z A B C D E F G H I J K L P Q R S U V W X Y Z A B C D E F G H I J K L P Q R S U V W X Y Z A B C D E F G H I J K L P Q R S T U V W X Y Z A B C D E F G H I J K L N P Q R S T U V W X Y Z A B C D E F G H I J K L N P Q R S T U V W X Y Z A B C D E F G H I J K L N O P Q R S T U V W X Y Z A B C D E F G H I J K L N O P Q R S T U V W X Y Z A B C D E F G H I J K L N O P Q R S T U V W X Y Z A B C D E F G H I J K L N O P Q R S T U V W X Y Z A B C D E F G H I J K L N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #25: G G G J G J G J G J G J G J G J G J C G J C F G J C F G J C F G I J C E F G I J C E F G I J Y C D E F G I J L M Y C D E F G I J L M N Y A C D E F G I J L M N T Y A C D E F G I J L M N P R T V Y A B C D E F G I J L M N P Q R T V Y A B C D E F G I J L M N O P Q R T V Y A B C D E F G I J L M N O P Q R T V Y A B C D E F G I J K L M N O P Q R T V Y A B C D E F G I J K L M N O P Q R T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W X Y A B C D E F G H I J K L M N O P Q R S T U V W XY\n",
      "Case #26: F F F F M F M F M F M F G M F G M F G M F G J M F G H J M F G H J M N F G H J M N F G H J L M N B F G H J K L M N O B E F G H J K L M N O P R B E F G H J K L M N O P R B D E F G H I J K L M N O P R B C D E F G H I J K L M N O P Q R B C D E F G H I J K L M N O P Q R B C D E F G H I J K L M N O P Q R B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P QR\n",
      "Case #27: B B H B D H B D F H J B D F H J B D F H J N B D F H J N B D F H J N B D F H J N B D F H J N B D F G H J N B D F G H J N B D F G H J N B D F G H J N B D E F G H J K L N B D E F G H J K L N B C D E F G H J K L M N B C D E F G H J K L M N B C D E F G H J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L M N A B C D E F G H I J K L MN\n",
      "Case #28: C C C C A C A C A C A C A C A C A C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B CD\n",
      "Case #29: C B C A BC\n",
      "Case #30: Z Z Z Z M Z M Q Z M Q Z M Q Z M Q Z M Q Z M Q Z M Q Z C M P Q Z C M P Q Z C M P Q U Z C M P Q U X Z C J K M P Q S U X Z C E J K M P Q R S U X Z C E J K M P Q R S U W X Z C E J K M O P Q R S U V W X Z C E J K M O P Q R S U V W X Z C E H J K M O P Q R S U V W X Z A C E H J K M O P Q R S U V W X Y Z A C E F H J K M O P Q R S U V W X Y Z A C E F H J K M O P Q R S U V W X Y Z A C D E F H J K M O P Q R S U V W X Y Z A C D E F H J K M O P Q R S U V W X Y Z A B C D E F H J K M N O P Q R S U V W X Y Z A B C D E F H J K L M N O P Q R S T U V W X Y Z A B C D E F H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #31: A A BC\n",
      "Case #32: R R R R R R R R R R R R R R R R R R R R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R J R H J R H J R H J R H J R H J R T H J R T G H J N R S T Z G H J N R S T X Z G H J M N R S T X Z G H J M N R S T X Z C G H J M N O R S T X Z B C G H J M N O R S T U V W X Z A B C F G H J M N O P R S T U V W X Y Z A B C F G H J L M N O P R S T U V W X Y Z A B C D E F G H J L M N O P Q R S T U V W X Y Z A B C D E F G H J L M N O P Q R S T U V W X Y Z A B C D E F G H J K L M N O P Q R S T U V W X Y Z A B C D E F G H J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #33: K K K K Q K Q K Q C K M N P Q R W C H K L M N P Q R W A B C G H K L M N P Q R W A B C D G H J K L M N P Q R W A B C D G H J K L M N P Q R W A B C D G H J K L M N P Q R T U W Z A B C D G H J K L M N P Q R T U W Z A B C D G H J K L M N P Q R T U W Z A B C D G H I J K L M N O P Q R T U V W Y Z A B C D G H I J K L M N O P Q R T U V W X Y Z A B C D E G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #34: D D D D C D B C D B C D B C D B C D B C D B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D I Z A B C D I K Z A B C D I K Z A B C D I K Z A B C D I K O Z A B C D I K O Z A B C D G I K O P R Z A B C D G I K O P R Z A B C D G I K M O P R X Z A B C D G I K L M O P R V W X Z A B C D E F G I K L M O P R S U V W X Z A B C D E F G H I J K L M O P R S U V W X Z A B C D E F G H I J K L M O P R S U V W X Z A B C D E F G H I J K L M N O P R S U V W X Z A B C D E F G H I J K L M N O P R S U V W X Z A B C D E F G H I J K L M N O P Q R S U V W X Y Z A B C D E F G H I J K L M N O P Q R S U V W X Y Z A B C D E F G H I J K L M N O P Q R S U V W X Y Z A B C D E F G H I J K L M N O P Q R S U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #35: L L L B C I L R B C I L R B C H I K L R A B C H I K L R A B C F H I K L N R A B C F H I K L N R A B C F H I K L N R A B C F H I K L N R A B C F H I K L N R A B C F H I K L N P Q R A B C E F H I K L N O P Q R A B C E F H I K L N O P Q R A B C D E F H I K L N O P Q R A B C D E F H I K L N O P Q R A B C D E F H I J K L N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P QR\n",
      "Case #36: A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A C E G I K M O Q S U W Y A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #37: B B C A BC\n",
      "Case #38: I K I K I K I K I K I K I K I K I K I K M I K M E F I K M E F I K L M O E F I K L M O E F I K L M O E F I K L M O Q A D E F H I K L M O Q A D E F H I K L M O Q A C D E F G H I K L M O Q A C D E F G H I K L M O Q A B C D E F G H I K L M O Q A B C D E F G H I K L M O Q A B C D E F G H I K L M N O P Q A B C D E F G H I K L M N O P Q A B C D E F G H I K L M N O P Q A B C D E F G H I K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O PQ\n",
      "Case #39: B B C A B C A BC\n",
      "Case #40: A A A A A A A A A A A C A C A C A C A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D A B C D U A B C D I O S U A B C D I J O S U A B C D I J L M O S U A B C D I J L M O S U X A B C D E G H I J K L M O S U X Y A B C D E G H I J K L M O S U V X Y Z A B C D E G H I J K L M O P S U V W X Y Z A B C D E F G H I J K L M O P Q S U V W X Y Z A B C D E F G H I J K L M O P Q S U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #41: A A A A A A A A A A A A A A A A A A A A A A A A A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #42: A C E G I A C E G I A C E G I A C E G I A C E G I A C E G I A C E G I A C E G I A B C D E F G H IJ\n",
      "Case #43: C I C I C I C I L C I L C I L C I L C I L C F I L C F I L M C F I L M N C F H I L M N C D F H I L M N C D F H I L M N C D F H I L M N P C D F H I L M N P B C D F H I L M N P A B C D F H I J L M N O P A B C D F H I J L M N O P A B C D F H I J L M N O P A B C D F G H I J L M N O P A B C D F G H I J L M N O P A B C D E F G H I J K L M N O P A B C D E F G H I J K L M N O P A B C D E F G H I J K L M N O P A B C D E F G H I J K L M N O P A B C D E F G H I J K L M N O P A B C D E F G H I J K L M N O P A B C D E F G H I J K L M N O P A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O PQ\n",
      "Case #44: A A A B C A BC\n",
      "Case #45: H H K H K H I K N H I K N F H I K N R X F H I K M N R X F H I K M N R X F H I J K M N R X Y C F H I J K M N R T X Y C E F H I J K M N O R T V X Y Z C E F G H I J K M N O Q R T V X Y Z C E F G H I J K M N O Q R T U V W X Y Z C E F G H I J K M N O Q R T U V W X Y Z B C D E F G H I J K M N O Q R T U V W X Y Z B C D E F G H I J K M N O Q R S T U V W X Y Z B C D E F G H I J K M N O Q R S T U V W X Y Z B C D E F G H I J K M N O Q R S T U V W X Y Z A B C D E F G H I J K M N O Q R S T U V W X Y Z A B C D E F G H I J K M N O P Q R S T U V W X Y Z A B C D E F G H I J K M N O P Q R S T U V W X Y Z A B C D E F G H I J K M N O P Q R S T U V W X Y Z A B C D E F G H I J K M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #46: M M M M M W J M W H J M W H J M Q W H J M Q W H J M Q U W H J M Q U W B H J M Q U W B H J L M Q U W B H J L M P Q U W X Z A B D F H J L M P Q U W X Z A B C D F H J L M P Q U W X Z A B C D F H J L M O P Q U W X Z A B C D E F H J L M N O P Q S U W X Z A B C D E F H J L M N O P Q S U V W X Z A B C D E F H J L M N O P Q R S U V W X Z A B C D E F G H I J L M N O P Q R S U V W X Z A B C D E F G H I J L M N O P Q R S U V W X Z A B C D E F G H I J L M N O P Q R S U V W X Z A B C D E F G H I J L M N O P Q R S U V W X Z A B C D E F G H I J L M N O P Q R S U V W X Z A B C D E F G H I J L M N O P Q R S U V W X Z A B C D E F G H I J L M N O P Q R S T U V W X Z A B C D E F G H I J L M N O P Q R S T U V W X Z A B C D E F G H I J L M N O P Q R S T U V W X Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #47: C B C A B C A BC\n",
      "Case #48: H H H H O D H O A D H O A D H O P A D F H O P A D F H O P Q A B D F H O P Q A B D F H K O P Q A B D F H J K L M O P Q A B D F H J K L M N O P Q A B D F H I J K L M N O P Q A B D E F H I J K L M N O P Q A B D E F H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P Q R A B C D E F G H I J K L M N O P QR\n",
      "Case #49: U P U B P U B P T U B P T U Z B P T U Z B M P Q T U Z B M P Q T U Z B C M P Q T U Y Z B C M P Q T U Y Z B C G K M O P Q T U Y Z B C G H I J K M N O P Q S T U Y Z B C E G H I J K M N O P Q S T U V X Y Z B C E G H I J K M N O P Q S T U V X Y Z B C E G H I J K M N O P Q S T U V X Y Z A B C E G H I J K M N O P Q S T U V X Y Z A B C E G H I J K M N O P Q S T U V X Y Z A B C D E G H I J K M N O P Q S T U V X Y Z A B C D E F G H I J K M N O P Q S T U V X Y Z A B C D E F G H I J K M N O P Q S T U V X Y Z A B C D E F G H I J K L M N O P Q S T U V X Y Z A B C D E F G H I J K L M N O P Q R S T U V X Y Z A B C D E F G H I J K L M N O P Q R S T U V X Y Z A B C D E F G H I J K L M N O P Q R S T U V X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z A B C D E F G H I J K L M N O P Q R S T U V W X YZ\n",
      "Case #50: B A B A B C A BC\n"
     ]
    }
   ],
   "source": [
    "with open(basepath + testset + '.in') as fin, open(basepath + testset + '.out', 'w') as fout:\n",
    "    T = int(fin.readline().rstrip('\\r\\n'))\n",
    "    for i in xrange(T):\n",
    "        N = int(fin.readline().rstrip('\\r\\n'))\n",
    "        P = map(int, fin.readline().rstrip('\\r\\n').split(' '))\n",
    "        \n",
    "        sol = do_solve(N, P)\n",
    "        \n",
    "        sol_string = 'Case #{}: {}'.format(i+1, sol)\n",
    "        fout.write(sol_string + '\\n')\n",
    "        print sol_string"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python2",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
