#include<stdio.h>
#include<string.h>
#include<fstream>
using namespace std;
int num[7][3000000];
int main()
{
int t,a,b,i,j,k,l,cnt,temp,fact;
for(j=1;j<10;j++)
{
    num[0][j]=num[1][j]=num[2][j]=num[3][j]=num[4][j]=num[5][j]=num[6][j]=j;
}
for(j=10;j<100;j++)
{
    num[0][j]=num[2][j]=num[3][j]=num[4][j]=num[5][j]=num[6][j]=j;
    temp=j%10;
    num[1][j]=(temp*10)+j/10;
}
for(j=100;j<1000;j++)
{
    num[0][j]=num[3][j]=num[4][j]=num[5][j]=num[6][j]=j;
    temp=j%10;
    num[1][j]=(temp*100)+(j/10);
    temp=num[1][j]%10;
    num[2][j]=(temp*100)+(num[1][j]/10);
}
for(j=1000;j<10000;j++)
{
    num[0][j]=num[4][j]=num[5][j]=num[6][j]=j;
    for(i=1;i<4;i++)
    {
        temp=num[i-1][j]%10;
        num[i][j]=(temp*1000)+(num[i-1][j]/10);
    }
}
for(j=10000;j<100000;j++)
{
    num[0][j]=num[5][j]=num[6][j]=j;
    for(i=1;i<5;i++)
    {
        temp=num[i-1][j]%10;
        num[i][j]=(temp*10000)+(num[i-1][j]/10);
    }
}
for(j=100000;j<1000000;j++)
{
    num[0][j]=num[6][j]=j;
    for(i=1;i<6;i++)
    {
        temp=num[i-1][j]%10;
        num[i][j]=(temp*100000)+(num[i-1][j]/10);
    }
}
for(j=1000000;j<2000500;j++)
{
    num[0][j]=j;
    for(i=1;i<7;i++)
    {
        temp=num[i-1][j]%10;
        num[i][j]=(temp*1000000)+(num[i-1][j]/10);
    }
}
freopen("C:\\Users\\Sameer\\Desktop\\C-small-attempt2.in","r",stdin);
freopen("C:\\Users\\Sameer\\Desktop\\output.out","w",stdout);
scanf("%d",&t);
for(i=1;i<=t;i++)
{
    cnt=0;
    scanf("%d%d",&a,&b);
    for(j=a;j<=b;j++)
    {
        for(k=1;k<7;k++)
        {
            if(num[k][j]<=b && num[k][j]>=a)
            {
                fact=1;
                for(l=0;l<k;l++)
                    if(num[k][j]==num[l][j])
                        fact=0;
                if(fact)cnt++;
            }
        }
    }
    printf("Case #%d: %d\n",i,cnt/2);
}
return 0;
}
