#include<iostream.h>
#include<fstream.h>
#include<conio.h>
#include<math.h>
main()
{
      char c[26],s[100],ch;
      int i,j,k,n,result[60],len,r,fl,in,count,o,p3;
      long a[60][2],sum=0,l,p,t,tmp,test[200000],test1[200000],p1;
      fstream f;
      f.open("C-small-attempt0.in",ios::in);
      f.get(ch);
      while(ch!='\n')
      {
      sum=sum*10+(((int)ch)-48);
      f.get(ch);
      }
      n=sum;
for(j=0;j<n;j++)
{
      result[j]=0;
      sum=0;
      k=0;
      f.get(ch);
      while(ch!='\n'&&!f.eof())
      {
      s[k++]=ch;
      f.get(ch);
      }
      s[k]='\0';
for(i=0;s[i]!='\0';i++)
{
		if(s[i]!=' ')
		{
		sum=(sum*10)+(((int)s[i])-48);
		}
		else
		{
			a[j][0]=sum;
			sum=0;
      }
}
a[j][1]=sum;
}
for(i=0;i<n;i++)
{
                k=-1;
                for(l=a[i][0];l<=a[i][1];l++)
                {
                         if(l>=10)
                         {
                                             fl=1;
                                            len=0;
                                             t=l;
                                             while(t!=0)
                                             {
                                                        len++;
                                                        t=t/10;
                                                        }
                                             p=10;
                                             o=1;
                                             while(o<(len-1))
                                             {
                                             p=p*10;
                                             o++;
                                             }
                                             tmp=l;
                                             count=0;
                                             p1=10;
                                             t=tmp;
                                             do
                                             {
                                             p1=10;  
                                             count=0;       
                                             if((p/p1)!=0&&(tmp/(p/p1))%10==0)
                                             {
                                             while((p/p1)!=0&&(tmp/(p/p1))%10==0)
                                             {
                                             count++;
                                             p1=p1*10;
                                             }
                                             t=tmp/p;
                                             r=tmp%p;
                                             t=r*10+t;
                                             p3=10;
                                             o=1;
                                             while(o<=count)
                                             {
                                             t=t*p3;
                                             o++;
                                             }
                                             tmp=t;
                                             }
                                             else
                                             {
                                             t=tmp/p;
                                             r=tmp%p;
                                             t=r*10+t;
                                             }
                                             if(t>=a[i][0]&&t<=a[i][1]&&t!=l)
                                             {
                                             for(j=0;j<=k;j++)
                                             {
                                             if((test[j]==t&&test1[j]==l)||(test1[j]==t&&test[j]==l))
                                             {
                                             fl=0;
                                             break;
                                             }}
                                             if(fl==1)
                                             {
                                             result[i]++;
                                             test[++k]=t;
                                             test1[k]=l;
                                             }}
                                             tmp=t;
                                             }while(l!=t);
                                             }}
                                             cout<<"Case #"<<(i+1)<<": "<<result[i]<<"\n";
                                             }
                                             
getch();
}
