#include<stdio.h>
#include<string.h>

int t,i,j,k,l,x,o,tt,d,xw,ow,dr,com;
char c[10][10],ch;
int main()
{
    freopen("A-large.in","r",stdin);
    freopen("output.txt","w",stdout);
    scanf("%d",&t);
    for(i=1;i<=t;i++)
    {
        d=xw=ow=com=0;
        dr=1;
        for(j=0;j<4;j++)
        {
            scanf("%s",c[j]);
        }
        for(j=0;j<4;j++)
        {
            x=o=tt=0;
            for(k=0;k<4;k++)
            {
                if(c[j][k]=='X')
                {
                    x++;
                }
                if(c[j][k]=='O')
                {
                    o++;
                }
                if(c[j][k]=='T')
                {
                    tt++;
                }
                if(c[j][k]=='.')
                {
                    d++;
                }
            }
            if((x>2)&&(x+tt==4))
            {
                xw=1;
                break;
            }
            if((o>2)&&(o+tt==4))
            {
                ow=1;
                break;
            }
        }
        for(j=0;j<4;j++)
        {
            x=o=tt=0;
            for(k=0;k<4;k++)
            {
                if(c[k][j]=='X')
                {
                    x++;
                }
                if(c[k][j]=='O')
                {
                    o++;
                }
                if(c[k][j]=='T')
                {
                    tt++;
                }
                if(c[k][j]=='.')
                {
                    d++;
                }
            }
            if((x>2)&&(x+tt==4))
            {
                xw=1;
                break;
            }
            if((o>2)&&(o+tt==4))
            {
                ow=1;
                break;
            }
        }
        x=o=tt=0;
        for(j=0;j<4;j++)
        {
            if(c[j][j]=='X')
            {
                x++;
            }
            if(c[j][j]=='O')
            {
                o++;
            }
            if(c[j][j]=='T')
            {
                tt++;
            }
            if(c[j][j]=='.')
            {
                d++;
            }
        }
        if((x>2)&&(x+tt==4))
        {
            xw=1;
        }
        if((o>2)&&(o+tt==4))
        {
            ow=1;
        }
        x=o=tt=0;
        for(j=0;j<4;j++)
        {
            if(c[j][3-j]=='X')
            {
                x++;
            }
            if(c[j][3-j]=='O')
            {
                o++;
            }
            if(c[j][3-j]=='T')
            {
                tt++;
            }
            if(c[j][3-j]=='.')
            {
                d++;
            }
        }
        if((x>2)&&(x+tt==4))
        {
            xw=1;
        }
        if((o>2)&&(o+tt==4))
        {
            ow=1;
        }
        if(xw==1)
        {
            printf("Case #%d: X won\n",i);
        }
        if(ow==1)
        {
            printf("Case #%d: O won\n",i);
        }
        if((xw==0)&&(ow==0))
        {
            if(d==0)
            {
                printf("Case #%d: Draw\n",i);
            }
            else
            {
                printf("Case #%d: Game has not completed\n",i);
            }
        }
    }
    return 0;
}
