#include <cstdio>
int main()
{
    char a[10],b[10],c[10],d[10];
    int i,j,k,l,n,check;
    scanf("%d",&n);
    for (i=0;i<n;i++)
    {
        check=2;
        scanf("%s",&a);
        scanf("%s",&b);
        scanf("%s",&c);
        scanf("%s",&d);
        if(a[0]=='X'||a[0]=='T')
        {
            if(a[1]=='X'||a[1]=='T')
            {
                if(a[2]=='X'||a[2]=='T')
                {
                    if(a[3]=='X'||a[3]=='T')
                    {
                        freopen("outputTTT.txt","a",stdout);
                        printf("Case #%d: X won\n",i+1);
                        fclose(stdout);
                        check=0;
                    }
                }
            }
        }
        if (check==2)
        {
            if(a[0]=='X'||a[0]=='T')
            {
                if(b[0]=='X'||b[0]=='T')
                {
                    if(c[0]=='X'||c[0]=='T')
                    {
                        if(d[0]=='X'||d[0]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(a[0]=='X'||a[0]=='T')
            {
                if(b[1]=='X'||b[1]=='T')
                {
                    if(c[2]=='X'||c[2]=='T')
                    {
                        if(d[3]=='X'||d[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(b[0]=='X'||b[0]=='T')
            {
                if(b[1]=='X'||b[1]=='T')
                {
                    if(b[2]=='X'||b[2]=='T')
                    {
                        if(b[3]=='X'||b[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(c[0]=='X'||c[0]=='T')
            {
                if(c[1]=='X'||c[1]=='T')
                {
                    if(c[2]=='X'||c[2]=='T')
                    {
                        if(c[3]=='X'||c[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(d[0]=='X'||d[0]=='T')
            {
                if(d[1]=='X'||d[1]=='T')
                {
                    if(d[2]=='X'||d[2]=='T')
                    {
                        if(d[3]=='X'||d[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(d[0]=='X'||d[0]=='T')
            {
                if(c[1]=='X'||c[1]=='T')
                {
                    if(b[2]=='X'||b[2]=='T')
                    {
                        if(a[3]=='X'||a[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }

        if(check==2)
        {
            if(a[1]=='X'||a[1]=='T')
            {
                if(b[1]=='X'||b[1]=='T')
                {
                    if(c[1]=='X'||c[1]=='T')
                    {
                        if(d[1]=='X'||d[1]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(a[2]=='X'||a[2]=='T')
            {
                if(b[2]=='X'||b[2]=='T')
                {
                    if(c[2]=='X'||c[2]=='T')
                    {
                        if(d[2]=='X'||d[2]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                            }
                        }
                    }
                }
            }
        if (check==2)
        {
            if(a[3]=='X'||a[3]=='T')
            {
                if(b[3]=='X'||b[3]=='T')
                {
                    if(c[3]=='X'||c[1]=='T')
                    {
                        if(d[3]=='X'||d[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: X won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if (check==2)
        {
            if(a[0]=='O'||a[0]=='T')
            {
                if(a[1]=='O'||a[1]=='T')
                {
                    if(a[2]=='O'||a[2]=='T')
                    {
                        if(a[3]=='O'||a[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if (check==2)
        {
            if(a[0]=='O'||a[0]=='T')
            {
                if(b[0]=='O'||b[0]=='T')
                {
                    if(c[0]=='O'||c[0]=='T')
                    {
                        if(d[0]=='O'||d[0]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(a[0]=='O'||a[0]=='T')
            {
                if(b[1]=='O'||b[1]=='T')
                {
                    if(c[2]=='O'||c[2]=='T')
                    {
                        if(d[3]=='O'||d[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(b[0]=='O'||b[0]=='T')
            {
                if(b[1]=='O'||b[1]=='T')
                {
                    if(b[2]=='O'||b[2]=='T')
                    {
                        if(b[3]=='O'||b[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(c[0]=='O'||c[0]=='T')
            {
                if(c[1]=='O'||c[1]=='T')
                {
                    if(c[2]=='O'||c[2]=='T')
                    {
                        if(c[3]=='O'||c[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(d[0]=='O'||d[0]=='T')
            {
                if(d[1]=='O'||d[1]=='T')
                {
                    if(d[2]=='O'||d[2]=='T')
                    {
                        if(d[3]=='O'||d[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(d[0]=='O'||d[0]=='T')
            {
                if(c[1]=='O'||c[1]=='T')
                {
                    if(b[2]=='O'||b[2]=='T')
                    {
                        if(a[3]=='O'||a[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }

        if(check==2)
        {
            if(a[1]=='O'||a[1]=='T')
            {
                if(b[1]=='O'||b[1]=='T')
                {
                    if(c[1]=='O'||c[1]=='T')
                    {
                        if(d[1]=='O'||d[1]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            if(a[2]=='O'||a[2]=='T')
            {
                if(b[2]=='O'||b[2]=='T')
                {
                    if(c[2]=='O'||c[2]=='T')
                    {
                        if(d[2]=='O'||d[2]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                            }
                        }
                    }
                }
            }
        if (check==2)
        {
            if(a[3]=='O'||a[3]=='T')
            {
                if(b[3]=='O'||b[3]=='T')
                {
                    if(c[3]=='O'||c[1]=='T')
                    {
                        if(d[3]=='O'||d[3]=='T')
                        {
                            freopen("outputTTT.txt","a",stdout);
                            printf("Case #%d: O won\n",i+1);
                            fclose(stdout);
                            check=0;
                        }
                    }
                }
            }
        }
        if(check==2)
        {
            for (j=0;j<4;j++)
            {
                if(a[j]=='.')
                {
                    check=1;
                }
                if(b[j]=='.')
                {
                    check=1;
                }
                if(c[j]=='.')
                {
                    check=1;
                }
                if(d[j]=='.')
                {
                    check=1;
                }
            }
            if(check==2)
            {
                freopen("outputTTT.txt","a",stdout);
                printf("Case #%d: Draw\n",i+1);
                fclose(stdout);
                check=0;
            }
            if(check==1)
            {
                freopen("outputTTT.txt","a",stdout);
                printf("Case #%d: Game has not completed\n",i+1);
                fclose(stdout);
                check=0;
            }
        }

    }
    return 0;
}
