{
 "metadata": {
  "name": "",
  "signature": "sha256:87aee9fa247c11a39df3905ee47950aabd9aa0ce1ce7d9f3b94a0dbb96c97b3e"
 },
 "nbformat": 3,
 "nbformat_minor": 0,
 "worksheets": [
  {
   "cells": [
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "task = \"T4\"\n",
      "f = open('input'+task+'.txt', 'r')\n",
      "n_tests = int(f.readline())\n",
      "def case():\n",
      "    global f\n",
      "    # read Smax\n",
      "    line = (f.readline()).split()\n",
      "    X = int(line[0])\n",
      "    R = int(line[1])\n",
      "    C = int(line[2])\n",
      "    \n",
      "    if X == 1:\n",
      "        return True\n",
      "    elif X == 2:\n",
      "        return R*C % 2 == 0\n",
      "    elif X == 3:\n",
      "        return R * C % 3 == 0 and R > 1 and C > 1\n",
      "    elif X == 4:\n",
      "        return R*C == 12 or R*C == 16"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 28
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "result = []\n",
      "for i in range(n_tests):\n",
      "    res = case()\n",
      "    name = \"GABRIEL\" if res else \"RICHARD\"\n",
      "    result.append(\"Case #\"+str(i+1)+\": \"+name)\n",
      "f.close()"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 29
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "result"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "metadata": {},
       "output_type": "pyout",
       "prompt_number": 21,
       "text": [
        "['Case #1: GABRIEL',\n",
        " 'Case #2: RICHARD',\n",
        " 'Case #3: RICHARD',\n",
        " 'Case #4: GABRIEL',\n",
        " 'Case #5: RICHARD',\n",
        " 'Case #6: RICHARD',\n",
        " 'Case #7: GABRIEL',\n",
        " 'Case #8: GABRIEL',\n",
        " 'Case #9: GABRIEL',\n",
        " 'Case #10: GABRIEL',\n",
        " 'Case #11: RICHARD',\n",
        " 'Case #12: RICHARD',\n",
        " 'Case #13: GABRIEL',\n",
        " 'Case #14: GABRIEL',\n",
        " 'Case #15: RICHARD',\n",
        " 'Case #16: RICHARD',\n",
        " 'Case #17: RICHARD',\n",
        " 'Case #18: RICHARD',\n",
        " 'Case #19: GABRIEL',\n",
        " 'Case #20: RICHARD',\n",
        " 'Case #21: RICHARD',\n",
        " 'Case #22: RICHARD',\n",
        " 'Case #23: RICHARD',\n",
        " 'Case #24: RICHARD',\n",
        " 'Case #25: RICHARD',\n",
        " 'Case #26: GABRIEL',\n",
        " 'Case #27: RICHARD',\n",
        " 'Case #28: RICHARD',\n",
        " 'Case #29: RICHARD',\n",
        " 'Case #30: RICHARD',\n",
        " 'Case #31: RICHARD',\n",
        " 'Case #32: RICHARD',\n",
        " 'Case #33: RICHARD',\n",
        " 'Case #34: RICHARD',\n",
        " 'Case #35: GABRIEL',\n",
        " 'Case #36: GABRIEL',\n",
        " 'Case #37: GABRIEL',\n",
        " 'Case #38: RICHARD',\n",
        " 'Case #39: RICHARD',\n",
        " 'Case #40: RICHARD',\n",
        " 'Case #41: GABRIEL',\n",
        " 'Case #42: RICHARD',\n",
        " 'Case #43: RICHARD',\n",
        " 'Case #44: RICHARD',\n",
        " 'Case #45: RICHARD',\n",
        " 'Case #46: RICHARD',\n",
        " 'Case #47: GABRIEL',\n",
        " 'Case #48: GABRIEL',\n",
        " 'Case #49: GABRIEL',\n",
        " 'Case #50: RICHARD',\n",
        " 'Case #51: RICHARD',\n",
        " 'Case #52: RICHARD',\n",
        " 'Case #53: RICHARD',\n",
        " 'Case #54: GABRIEL',\n",
        " 'Case #55: GABRIEL',\n",
        " 'Case #56: RICHARD',\n",
        " 'Case #57: RICHARD',\n",
        " 'Case #58: GABRIEL',\n",
        " 'Case #59: RICHARD',\n",
        " 'Case #60: RICHARD',\n",
        " 'Case #61: RICHARD',\n",
        " 'Case #62: RICHARD',\n",
        " 'Case #63: RICHARD',\n",
        " 'Case #64: RICHARD']"
       ]
      }
     ],
     "prompt_number": 21
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [
      "# write to file\n",
      "fout = open('output'+task+'.txt', 'w')\n",
      "for line in result:\n",
      "    print(line)\n",
      "    fout.write(line+'\\n')\n",
      "fout.close()"
     ],
     "language": "python",
     "metadata": {},
     "outputs": [
      {
       "output_type": "stream",
       "stream": "stdout",
       "text": [
        "Case #1: GABRIEL\n",
        "Case #2: RICHARD\n",
        "Case #3: RICHARD\n",
        "Case #4: GABRIEL\n",
        "Case #5: RICHARD\n",
        "Case #6: GABRIEL\n",
        "Case #7: RICHARD\n",
        "Case #8: RICHARD\n",
        "Case #9: GABRIEL\n",
        "Case #10: RICHARD\n",
        "Case #11: RICHARD\n",
        "Case #12: RICHARD\n",
        "Case #13: RICHARD\n",
        "Case #14: RICHARD\n",
        "Case #15: RICHARD\n",
        "Case #16: RICHARD\n",
        "Case #17: RICHARD\n",
        "Case #18: RICHARD\n",
        "Case #19: RICHARD\n",
        "Case #20: RICHARD\n",
        "Case #21: RICHARD\n",
        "Case #22: RICHARD\n",
        "Case #23: GABRIEL\n",
        "Case #24: RICHARD\n",
        "Case #25: RICHARD\n",
        "Case #26: RICHARD\n",
        "Case #27: GABRIEL\n",
        "Case #28: GABRIEL\n",
        "Case #29: RICHARD\n",
        "Case #30: GABRIEL\n",
        "Case #31: GABRIEL\n",
        "Case #32: RICHARD\n",
        "Case #33: GABRIEL\n",
        "Case #34: RICHARD\n",
        "Case #35: GABRIEL\n",
        "Case #36: GABRIEL\n",
        "Case #37: RICHARD\n",
        "Case #38: RICHARD\n",
        "Case #39: RICHARD\n",
        "Case #40: RICHARD\n",
        "Case #41: GABRIEL\n",
        "Case #42: GABRIEL\n",
        "Case #43: GABRIEL\n",
        "Case #44: GABRIEL\n",
        "Case #45: RICHARD\n",
        "Case #46: RICHARD\n",
        "Case #47: RICHARD\n",
        "Case #48: GABRIEL\n",
        "Case #49: GABRIEL\n",
        "Case #50: RICHARD\n",
        "Case #51: RICHARD\n",
        "Case #52: GABRIEL\n",
        "Case #53: GABRIEL\n",
        "Case #54: RICHARD\n",
        "Case #55: RICHARD\n",
        "Case #56: RICHARD\n",
        "Case #57: RICHARD\n",
        "Case #58: RICHARD\n",
        "Case #59: RICHARD\n",
        "Case #60: RICHARD\n",
        "Case #61: RICHARD\n",
        "Case #62: RICHARD\n",
        "Case #63: RICHARD\n",
        "Case #64: RICHARD\n"
       ]
      }
     ],
     "prompt_number": 25
    },
    {
     "cell_type": "code",
     "collapsed": false,
     "input": [],
     "language": "python",
     "metadata": {},
     "outputs": [],
     "prompt_number": 22
    }
   ],
   "metadata": {}
  }
 ]
}