'''
Created on Apr 14, 2012

@author: ABEL
'''

'''
The language map was generated by running the following:

language = dict(zip('abcdefghijklmnopqrstuvwxyz','                          '))
language.update(dict(zip('ejp mysljylc kd kxveddknmc re jsicpdrysi','our language is impossible to understand')))
language.update(dict(zip('rbcpc ypc rtcsra dkh wyfrepkym veddknkmkrkcd','there are twenty six factorial possibilities')))
language.update(dict(zip('de kr kd eoya kw aej tysr re ujdr lkgc jv','so it is okay if you want to just give up')))

And since it's given that z->q, then q->z.
'''

language_map = {'a': 'y', 'b': 'h', 'c': 'e', 'd': 's',
				'e': 'o',  'f': 'c', 'g': 'v', 'h': 'x',
				'i': 'd', 'j': 'u', 'k': 'i', 'l': 'g',
				'm': 'l', 'n': 'b', 'o': 'k', 'p': 'r',
				'q': 'z', 'r': 't', 's': 'n', 't': 'w',
				'u': 'j', 'v': 'p', 'w': 'f', 'x': 'm',
				'y': 'a', 'z': 'q', ' ': ' '}

def translate(inline):
	return ''.join([language_map.get(c) for c in inline])

def handle_file(infile):
	num_cases = int(infile.readline())
	cases = infile.readlines()
	
	for i in range(num_cases):
		line = translate(cases[i].strip())
		print('Case #{0}: {1}'.format(i + 1, line))

if __name__ == '__main__':
	with open("A-small-attempt1.in", "r") as f:
		handle_file(f)