import re 

f = open('test.in', 'r')
o = open('test.out', 'w')

T = int(f.readline().strip())
case = 1
for t in xrange(T):
	line = f.readline().strip()

	line = re.sub("y",":00", line)
	line = re.sub("q",":99", line)
	line = re.sub("z",":98", line)
	line = re.sub("n",":01", line)
	line = re.sub("f",":02", line)
	line = re.sub("i",":03", line)
	line = re.sub("c",":04", line)
	line = re.sub("w",":05", line)
	line = re.sub("l",":06", line)
	line = re.sub("b",":07", line)
	line = re.sub("k",":08", line)
	line = re.sub("u",":09", line)
	line = re.sub("o",":10", line)
	line = re.sub("m",":11", line)
	line = re.sub("x",":12", line)
	line = re.sub("s",":13", line)
	line = re.sub("e",":14", line)
	line = re.sub("v",":15", line)
	line = re.sub("p",":16", line)
	line = re.sub("d",":17", line)
	line = re.sub("r",":18", line)
	line = re.sub("j",":19", line)
	line = re.sub("g",":20", line)
	line = re.sub("t",":21", line)
	line = re.sub("h",":22", line)
	line = re.sub("a",":23", line)

	line = re.sub(":00","a", line)
	line = re.sub(":99","z", line)
	line = re.sub(":98","q", line)
	line = re.sub(":01","b", line)
	line = re.sub(":02","c", line)
	line = re.sub(":03","d", line)
	line = re.sub(":04","e", line)
	line = re.sub(":05","f", line)
	line = re.sub(":06","g", line)
	line = re.sub(":07","h", line)
	line = re.sub(":08","i", line)
	line = re.sub(":09","j", line)
	line = re.sub(":10","k", line)
	line = re.sub(":11","l", line)
	line = re.sub(":12","m", line)
	line = re.sub(":13","n", line)
	line = re.sub(":14","o", line)
	line = re.sub(":15","p", line)
	line = re.sub(":16","r", line)
	line = re.sub(":17","s", line)
	line = re.sub(":18","t", line)
	line = re.sub(":19","u", line)
	line = re.sub(":20","v", line)
	line = re.sub(":21","w", line)
	line = re.sub(":22","x", line)
	line = re.sub(":23","y", line)
	line = "Case #%s: %s\n" % (case, line)
	case = case + 1

	print line
	o.write(line)
