#include<cstdio>
char s[200][200],c[200];
int main(){
  int t,tt,n,k,cn,rw,bw,i,j;
  scanf("%d",&t);
  for(tt=1;tt<=t;tt++){
    rw=0;
    bw=0;
    scanf("%d",&n);
    scanf("%d",&k);
    for(i=0;i<n;i++){
      for(j=0;j<n;j++){
	s[i][j]='.';
      }
    }
    for(i=0;i<n;i++){
      scanf("%s",c);
      cn=0;
      for(j=n-1;j>=0;j--){
	if(c[j]!='.'){
	  s[i][cn++]=c[j];
	}
      }
    }
    //BLUE
    for(i=0;i<n;i++){
      cn=0;
      for(j=0;j<n;j++){
	if(s[i][j]=='B'){
	  cn++;
	  if(cn>=k){
	    bw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(j=0;j<n;j++){
      cn=0;
      for(i=0;i<n;i++){
	if(s[i][j]=='B'){
	  cn++;
	  if(cn>=k){
	    bw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=0;i<n;i++){
      for(j=0;i+j<n;j++){
	if(s[i+j][j]=='B'){
	  cn++;
	  if(cn>=k){
	    bw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=1;i<n;i++){
      for(j=0;i+j<n;j++){
	if(s[j][i+j]=='B'){
	  cn++;
	  if(cn>=k){
	    bw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=0;i<n;i++){
      for(j=0;j<=i;j++){
	if(s[i-j][j]=='B'){
	  cn++;
	  if(cn>=k){
	    bw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=1;i<n;i++){
      for(j=0;n-i-j>=0;j++){
	if(s[n-i-j][i+j]=='B'){
	  cn++;
	  if(cn>=k){
	    bw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    //RED
    for(i=0;i<n;i++){
      cn=0;
      for(j=0;j<n;j++){
	if(s[i][j]=='R'){
	  cn++;
	  if(cn>=k){
	    rw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(j=0;j<n;j++){
      cn=0;
      for(i=0;i<n;i++){
	if(s[i][j]=='R'){
	  cn++;
	  if(cn>=k){
	    rw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=0;i<n;i++){
      for(j=0;i+j<n;j++){
	if(s[i+j][j]=='R'){
	  cn++;
	  if(cn>=k){
	    rw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=1;i<n;i++){
      for(j=0;i+j<n;j++){
	if(s[j][i+j]=='R'){
	  cn++;
	  if(cn>=k){
	    rw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=0;i<n;i++){
      for(j=0;j<=i;j++){
	if(s[i-j][j]=='R'){
	  cn++;
	  if(cn>=k){
	    rw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    for(i=1;i<n;i++){
      for(j=0;n-i-j>=0;j++){
	if(s[n-i-j][i+j]=='R'){
	  cn++;
	  if(cn>=k){
	    rw=1;
	  }
	}else{cn=0;}
      }cn=0;
    }
    printf("Case #%d: ",tt);
    if(bw&&rw){
      printf("Both\n");
    }else if(bw){
      printf("Blue\n");
    }else if(rw){
      printf("Red\n");
    }else{
      printf("Neither\n");
    }
  }
}