reated on Apr 7, 2017

@author: davidkogosov
'''
import unittest
from test import infinite_reload

count = 1

class Test(unittest.TestCase):


        def setUp(self):
                
                        f = open('/Users/davidkogosov/Downloads/A-small-attempt0.in')
                                num = int(f.readline())
                                        print 'num', num
                                                for i in range(num):
                                                            l = f.readline()
                                                                        elms = l.split()
                                                                                    #print elms[0], elms[1]
                                                                                                self.solve(elms[0], int(elms[1]))
                                                                                                        f.close()
                                                                                                                pass


                                                                                                                    def tearDown(self):
                                                                                                                            pass

                                                                                                                                def flip1(self, test, j):
                                                                                                                                        if test[j] =='+': return '-'
                                                                                                                                                else: return '+'
                                                                                                                                                        
                                                                                                                                                            def flip(self, test, i, k):
                                                                                                                                                                    output = ""
                                                                                                                                                                            
                                                                                                                                                                                    for j in range(i):
                                                                                                                                                                                                output += test[j]
                                                                                                                                                                                                            
                                                                                                                                                                                                                    for j in range(i, i+k):
                                                                                                                                                                                                                                output += self.flip1(test, j)
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                for j in range(i+k, len(test)):
                                                                                                                                                                                                                                                            output += test[j]
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                            #print "before", test, "after", output
                                                                                                                                                                                                                                                                                    return output
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                     def test1(self):
                                                                                                                                                                                                                                                                                                             pass
                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                      def grow_dict(self, dict, n, k):
                                                                                                                                                                                                                                                                                                                              ln = len(dict)
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                              for key in dict.keys():
                                                                                                                                                                                                                                                                                                                                                          for i in range(n-k+1):
                                                                                                                                                                                                                                                                                                                                                                          tmp = self.flip(key, i, k)
                                                                                                                                                                                                                                                                                                                                                                                          if tmp in dict: pass
                                                                                                                                                                                                                                                                                                                                                                                                          else: dict[tmp] =dict[key] + 1
                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                  return len(dict) == ln
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                  def solve(self, test, k):
                                                                                                                                                                                                                                                                                                                                                                                                                                                          global count
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  #print "test", test
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          #print "k", k
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  n = len(test)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  dict = {test: 0}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          while False == self.grow_dict(dict, n, k):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pass
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              #print len(dict)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      #for key in  dict.keys():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              #    print key, dict[key]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              plus =   "".join( ['+'] *n)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              output = "Case #" + str(count) +":"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if not plus in dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  print output, 'IMPOSSIBLE'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      print output, dict[plus]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      count += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  #import sys;sys.argv = ['', 'Test.test1']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      unittest.main()
