{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Case #1: 129\n",
      "Case #2: 999\n",
      "Case #3: 7\n",
      "Case #4: 159\n",
      "Case #5: 899\n",
      "Case #6: 199\n",
      "Case #7: 599\n",
      "Case #8: 289\n",
      "Case #9: 899\n",
      "Case #10: 799\n",
      "Case #11: 399\n",
      "Case #12: 799\n",
      "Case #13: 689\n",
      "Case #14: 599\n",
      "Case #15: 459\n",
      "Case #16: 799\n",
      "Case #17: 699\n",
      "Case #18: 599\n",
      "Case #19: 389\n",
      "Case #20: 59\n",
      "Case #21: 159\n",
      "Case #22: 699\n",
      "Case #23: 9\n",
      "Case #24: 499\n",
      "Case #25: 789\n",
      "Case #26: 799\n",
      "Case #27: 569\n",
      "Case #28: 499\n",
      "Case #29: 899\n",
      "Case #30: 289\n",
      "Case #31: 499\n",
      "Case #32: 499\n",
      "Case #33: 999\n",
      "Case #34: 399\n",
      "Case #35: 267\n",
      "Case #36: 479\n",
      "Case #37: 799\n",
      "Case #38: 679\n",
      "Case #39: 899\n",
      "Case #40: 399\n",
      "Case #41: 579\n",
      "Case #42: 589\n",
      "Case #43: 389\n",
      "Case #44: 677\n",
      "Case #45: 799\n",
      "Case #46: 399\n",
      "Case #47: 24\n",
      "Case #48: 189\n",
      "Case #49: 39\n",
      "Case #50: 899\n",
      "Case #51: 589\n",
      "Case #52: 899\n",
      "Case #53: 899\n",
      "Case #54: 779\n",
      "Case #55: 279\n",
      "Case #56: 259\n",
      "Case #57: 369\n",
      "Case #58: 599\n",
      "Case #59: 259\n",
      "Case #60: 789\n",
      "Case #61: 258\n",
      "Case #62: 699\n",
      "Case #63: 399\n",
      "Case #64: 346\n",
      "Case #65: 499\n",
      "Case #66: 479\n",
      "Case #67: 499\n",
      "Case #68: 899\n",
      "Case #69: 599\n",
      "Case #70: 379\n",
      "Case #71: 699\n",
      "Case #72: 339\n",
      "Case #73: 345\n",
      "Case #74: 599\n",
      "Case #75: 889\n",
      "Case #76: 669\n",
      "Case #77: 699\n",
      "Case #78: 699\n",
      "Case #79: 799\n",
      "Case #80: 39\n",
      "Case #81: 399\n",
      "Case #82: 1\n",
      "Case #83: 899\n",
      "Case #84: 799\n",
      "Case #85: 369\n",
      "Case #86: 19\n",
      "Case #87: 699\n",
      "Case #88: 349\n",
      "Case #89: 159\n",
      "Case #90: 499\n",
      "Case #91: 359\n",
      "Case #92: 699\n",
      "Case #93: 899\n",
      "Case #94: 166\n",
      "Case #95: 259\n",
      "Case #96: 399\n",
      "Case #97: 399\n",
      "Case #98: 299\n",
      "Case #99: 399\n",
      "Case #100: 599\n"
     ]
    }
   ],
   "source": [
    "def lee(N):\n",
    "    N=int(N)\n",
    "    N=str(N)\n",
    "    if(len(N)==1):\n",
    "        return N\n",
    "    \n",
    "    elif(len(N)==2):\n",
    "        if(int(N)==10):\n",
    "            N=int(N)-1\n",
    "            return N\n",
    "        else:\n",
    "            \n",
    "            pa=N[0]\n",
    "            pb=N[1]\n",
    "            if(pa<=pb):\n",
    "                return N\n",
    "            elif(pa>pb):\n",
    "                while(1):\n",
    "                    N = int(N)-1\n",
    "                    N=str(N)\n",
    "                    pa_=N[0]\n",
    "                    pb_=N[1]\n",
    "                    if(pa_<pb_):\n",
    "                        return N\n",
    "                        break\n",
    "                    else:\n",
    "                        continue\n",
    "            elif(pa==pb):\n",
    "                return N\n",
    "            \n",
    "            \n",
    "    elif(len(N)==3):\n",
    "        if(int(N)==100):\n",
    "            N=int(N)-1\n",
    "            return N\n",
    "        else:\n",
    "            \n",
    "            pa=N[0]\n",
    "            pb=N[1]\n",
    "            pc=N[2]\n",
    "            if(int(N[1])==0):\n",
    "                aux=str(int(N[0])-1)\n",
    "                N=str(aux)+str(99)\n",
    "                return N\n",
    "            elif(pa<=pb and pb<=pc):\n",
    "                return N\n",
    "            elif(pa>pb or pb>pc):\n",
    "                while(1):\n",
    "                    N=int(N)-1\n",
    "                    N=str(N)\n",
    "                    pa_=N[0]\n",
    "                    pb_=N[1]\n",
    "                    pc_=N[2]\n",
    "                    if(pa_<=pb_ and pb_<=pc_):\n",
    "                        return N\n",
    "                        break\n",
    "                    else:\n",
    "                        continue\n",
    "       \n",
    "    elif(int(N)==1000):\n",
    "        N=int(N)-1\n",
    "        return N\n",
    "                \n",
    "if __name__ == \"__main__\":\n",
    "    archivo = open(\"inin.in\",\"r\")\n",
    "    contenido = archivo.readlines()\n",
    "    i=1\n",
    "    for k in range(1,101):\n",
    "        N = contenido[k]\n",
    "        N = str(N)\n",
    "        case=lee(N)\n",
    "        output=open(\"small.txt\", \"a\")\n",
    "        output.write(\"Case#\"+str(i)+\":\"+str(case))\n",
    "        print(\"Case #\"+str(i)+\": \"+str(case))\n",
    "        i=i+1\n",
    "    output.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
