{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Case #1: 129\n",
      "Case #2: 999\n",
      "Case #3: 7\n",
      "Case #4: 279\n",
      "Case #5: 489\n",
      "Case #6: 499\n",
      "Case #7: 599\n",
      "Case #8: 199\n",
      "Case #9: 689\n",
      "Case #10: 569\n",
      "Case #11: 469\n",
      "Case #12: 349\n",
      "Case #13: 249\n",
      "Case #14: 347\n",
      "Case #15: 89\n",
      "Case #16: 699\n",
      "Case #17: 399\n",
      "Case #18: 499\n",
      "Case #19: 599\n",
      "Case #20: 39\n",
      "Case #21: 689\n",
      "Case #22: 699\n",
      "Case #23: 139\n",
      "Case #24: 679\n",
      "Case #25: 599\n",
      "Case #26: 679\n",
      "Case #27: 599\n",
      "Case #28: 699\n",
      "Case #29: 699\n",
      "Case #30: 099\n",
      "Case #31: 499\n",
      "Case #32: 569\n",
      "Case #33: 888\n",
      "Case #34: 678\n",
      "Case #35: 899\n",
      "Case #36: 699\n",
      "Case #37: 899\n",
      "Case #38: 459\n",
      "Case #39: 123\n",
      "Case #40: 139\n",
      "Case #41: 259\n",
      "Case #42: 5\n",
      "Case #43: 489\n",
      "Case #44: 589\n",
      "Case #45: 79\n",
      "Case #46: 699\n",
      "Case #47: 199\n",
      "Case #48: 099\n",
      "Case #49: 899\n",
      "Case #50: 899\n",
      "Case #51: 249\n",
      "Case #52: 889\n",
      "Case #53: 159\n",
      "Case #54: 778\n",
      "Case #55: 999\n",
      "Case #56: 579\n",
      "Case #57: 699\n",
      "Case #58: 69\n",
      "Case #59: 599\n",
      "Case #60: 136\n",
      "Case #61: 149\n",
      "Case #62: 259\n",
      "Case #63: 799\n",
      "Case #64: 599\n",
      "Case #65: 499\n",
      "Case #66: 349\n",
      "Case #67: 299\n",
      "Case #68: 379\n",
      "Case #69: 117\n",
      "Case #70: 279\n",
      "Case #71: 269\n",
      "Case #72: 155\n",
      "Case #73: 127\n",
      "Case #74: 899\n",
      "Case #75: 799\n",
      "Case #76: 299\n",
      "Case #77: 1\n",
      "Case #78: 689\n",
      "Case #79: 599\n",
      "Case #80: 899\n",
      "Case #81: 179\n",
      "Case #82: 459\n",
      "Case #83: 799\n",
      "Case #84: 377\n",
      "Case #85: 599\n",
      "Case #86: 899\n",
      "Case #87: 289\n",
      "Case #88: 489\n",
      "Case #89: 111\n",
      "Case #90: 799\n",
      "Case #91: 699\n",
      "Case #92: 799\n",
      "Case #93: 789\n",
      "Case #94: 799\n",
      "Case #95: 799\n",
      "Case #96: 49\n",
      "Case #97: 777\n",
      "Case #98: 699\n",
      "Case #99: 579\n",
      "Case #100: 799\n"
     ]
    }
   ],
   "source": [
    "def lee(N):\n",
    "    N=int(N)\n",
    "    N=str(N)\n",
    "    if(len(N)==1):\n",
    "        return N\n",
    "    \n",
    "    elif(len(N)==2):\n",
    "        if(int(N)==10):\n",
    "            N=int(N)-1\n",
    "            return N\n",
    "        else:\n",
    "            \n",
    "            a=N[0]\n",
    "            b=N[1]\n",
    "            if(a<=b):\n",
    "                return N\n",
    "            elif(a>b):\n",
    "                while(1):\n",
    "                    N = int(N)-1\n",
    "                    N=str(N)\n",
    "                    a_=N[0]\n",
    "                    b_=N[1]\n",
    "                    if(a_<b_):\n",
    "                        return N\n",
    "                        break\n",
    "                    else:\n",
    "                        continue\n",
    "            elif(a==b):\n",
    "                return N\n",
    "            \n",
    "            \n",
    "            \n",
    "            \n",
    "    elif(len(N)==3):\n",
    "        if(int(N)==100):\n",
    "            N=int(N)-1\n",
    "            return N\n",
    "        else:\n",
    "            a=N[0]\n",
    "            b=N[1]\n",
    "            c=N[2]\n",
    "            if(int(N[1])==0):\n",
    "                aux=str(int(N[0])-1)\n",
    "                N=str(aux)+str(99)\n",
    "                return N\n",
    "            elif(a<=b and b<=c):\n",
    "                return N\n",
    "            elif(a>b or b>c):\n",
    "                while(1):\n",
    "                    N=int(N)-1\n",
    "                    N=str(N)\n",
    "                    a_=N[0]\n",
    "                    b_=N[1]\n",
    "                    c_=N[2]\n",
    "                    if(a_<=b_ and b_<=c_):\n",
    "                        return N\n",
    "                        break\n",
    "                    else:\n",
    "                        continue\n",
    "            \n",
    "            \n",
    "    elif(int(N)==1000):\n",
    "        N=int(N)-1\n",
    "        return N\n",
    "        \n",
    "\n",
    "    elif(a==b):\n",
    "        return N\n",
    "\n",
    "\n",
    "\n",
    "                \n",
    "if __name__ == \"__main__\":\n",
    "    archivo = open(\"ss.in\",\"r\")\n",
    "    contenido = archivo.readlines()\n",
    "    i=1\n",
    "    for k in range(1,101):\n",
    "        N = contenido[k]\n",
    "        N = str(N)\n",
    "        caso=lee(N)\n",
    "        \n",
    "        print(\"Case #\"+str(i)+\": \"+str(caso))\n",
    "        i=i+1\n",
    "    output.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
