{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import sys"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "sys.setrecursionlimit(2000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 154,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def check(cols, res):\n",
    "    #print cols, res\n",
    "    assert len(res) == sum(cols)\n",
    "    \n",
    "    for i in range(6):\n",
    "        assert(cols[i] == sum(1 for x in res if x == \"ROYGBV\"[i]))\n",
    "        \n",
    "    for i in range(len(res)-1):\n",
    "        assert res[i] != res[i+1]\n",
    "        \n",
    "    assert res[0] != res[-1]\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 180,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def check2(cols):\n",
    "    a = sorted(cols, reverse=True)\n",
    "    #print cols, a\n",
    "    assert(a[0] > sum(a[1:]))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 200,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def parse(text):\n",
    "    T = int(text.next())\n",
    "    for i in range(T):\n",
    "        cols = [int(x) for x in text.next().rstrip().split(\" \")[1:]]\n",
    "        \n",
    "        res = solveouter(cols)\n",
    "        if res is None:\n",
    "            check2(cols)\n",
    "            res = \"IMPOSSIBLE\"\n",
    "        else:\n",
    "            res = \"\".join([\"ROYGBV\"[x] for x in res])\n",
    "            check(cols, res)\n",
    "            \n",
    "        print \"Case #%d: %s\" % (i+1, res)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 201,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import copy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 208,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def solveouter(cols):\n",
    "    a = sorted(cols, reverse=True)\n",
    "    if a[0] > sum(a[1:]):\n",
    "        return None\n",
    "    else:\n",
    "        return solve(cols, [], [])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 219,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "def solve(cols, dontstart, dontend):\n",
    "    #print cols, dontstart, dontend\n",
    "    \n",
    "    if sum(cols) == 1:\n",
    "        for i in range(6):\n",
    "            if cols[i] == 1:\n",
    "                if i not in dontstart and i not in dontend:\n",
    "                    return [i]\n",
    "        return None\n",
    "    \n",
    "    options = []\n",
    "    for i in range(6):\n",
    "        if cols[i] != 0 and i not in dontstart:\n",
    "            options.append((cols[i], i in dontend, i))\n",
    "    \n",
    "    options = sorted(options, reverse=True)\n",
    "    \n",
    "    #if options[0][0] > sum(cols) - options[0][0]:\n",
    "    #    return None\n",
    "    \n",
    "    #print \"opt\", options\n",
    "    for (_,_, i) in options:\n",
    "        newcols = copy.copy(cols)\n",
    "        newcols[i] -= 1\n",
    "        newdontstart = [i-1%6, i, i+1%6]\n",
    "        newdontend = dontend if dontend else newdontstart\n",
    "\n",
    "        res = solve(newcols, newdontstart, newdontend)\n",
    "        if res:\n",
    "            return [i] + res\n",
    "\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 220,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[(4, True, 1), (4, False, 1)]"
      ]
     },
     "execution_count": 220,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "sorted([(4,True,1), (4,False,1)], reverse = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 221,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[4, 0, 3, 0, 4, 2]"
      ]
     },
     "execution_count": 221,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "solve([2,0,1,1,2,0], [], [])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 222,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "TEXT = \"\"\"4\n",
    "6 2 0 2 0 2 0\n",
    "3 1 0 2 0 0 0\n",
    "6 2 0 1 1 2 0\n",
    "4 0 0 2 0 0 2\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 223,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Case #1: BYRBYR\n",
      "Case #2: IMPOSSIBLE\n",
      "Case #3: BRGRBY\n",
      "Case #4: VYVY\n"
     ]
    }
   ],
   "source": [
    "parse(x for x in TEXT.splitlines())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 225,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Case #1: BYRBYR\n",
      "Case #2: IMPOSSIBLE\n",
      "Case #3: IMPOSSIBLE\n",
      "Case #4: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBR\n",
      "Case #5: IMPOSSIBLE\n",
      "Case #6: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBY\n",
      "Case #7: BRBRBRBYBRBYR\n",
      "Case #8: BYBYBY\n",
      "Case #9: YRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #10: RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #11: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBR\n",
      "Case #12: IMPOSSIBLE\n",
      "Case #13: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #14: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #15: BYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #16: IMPOSSIBLE\n",
      "Case #17: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYR\n",
      "Case #18: RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #19: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #20: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBRYBRYBR\n",
      "Case #21: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #22: IMPOSSIBLE\n",
      "Case #23: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #24: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #25: YBYR\n",
      "Case #26: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #27: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #28: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #29: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #30: IMPOSSIBLE\n",
      "Case #31: RYRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBY\n",
      "Case #32: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #33: BRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #34: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #35: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #36: YBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #37: RBRYRBY\n",
      "Case #38: RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBY\n",
      "Case #39: RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #40: IMPOSSIBLE\n",
      "Case #41: IMPOSSIBLE\n",
      "Case #42: IMPOSSIBLE\n",
      "Case #43: RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #44: YRYRYRYRYRYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #45: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #46: IMPOSSIBLE\n",
      "Case #47: BYBR\n",
      "Case #48: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #49: RBRY\n",
      "Case #50: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #51: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #52: YRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #53: BYR\n",
      "Case #54: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #55: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #56: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #57: YRYR\n",
      "Case #58: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYR\n",
      "Case #59: BRBR\n",
      "Case #60: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #61: IMPOSSIBLE\n",
      "Case #62: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #63: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBY\n",
      "Case #64: BRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #65: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #66: YBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYR\n",
      "Case #67: YBYBYBYBYBYBYBYBYBYBYBYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #68: IMPOSSIBLE\n",
      "Case #69: YBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #70: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #71: IMPOSSIBLE\n",
      "Case #72: IMPOSSIBLE\n",
      "Case #73: IMPOSSIBLE\n",
      "Case #74: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #75: IMPOSSIBLE\n",
      "Case #76: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYR\n",
      "Case #77: RYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #78: RBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBY\n",
      "Case #79: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #80: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #81: IMPOSSIBLE\n",
      "Case #82: RYRYRYRYRYRYRYRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #83: YRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #84: YRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #85: BRBYR\n",
      "Case #86: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #87: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #88: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #89: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #90: YBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #91: BRBYBR\n",
      "Case #92: RBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBRYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBY\n",
      "Case #93: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #94: YRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBYRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBRYBR\n",
      "Case #95: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #96: IMPOSSIBLE\n",
      "Case #97: BYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #98: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYRBYR\n",
      "Case #99: BRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYBRBYRBYRBYR\n"
     ]
    }
   ],
   "source": [
    "parse(open(\"C:\\Users\\mheik\\Downloads\\B-small-attempt2.in\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [Root]",
   "language": "python",
   "name": "Python [Root]"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
