/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author Maria
 */

/*
I am but a farce, a satire of stability
Insecurity is an uphill struggle, it's me versus the world
The shore still starves,
For another,

Novel of my shipwrecked being tied up dried alive still breathing
The sands of time, from me are running out,
my hands shake, in apprehension,
Of every action I'm guilty of playing the victim,
The shore still starves,
For another,

Novel of my shipwrecked being tied up dried alive still breathing
The sands of time, for me are running out.

Just like the embrace of arms that made you
They'll surely destroy you.
Just like the embrace of arms that made you
They'll surely destroy you.

It's time for your panic,
Then it kills and makes, you manic,

Making its way inside - relax, it's alright,
Making its way inside - relax, it's alright
Panic grips your frantic breathing
I can't breathe, I can't breathe,i cant breathe!

Just like the embrace of arms that made you
They'll surely destroy you.
Just like the embrace of arms that made you
They'll surely destroy you.

Just like the embrace of arms that made you
They'll surely destroy you.
Just like the embrace of arms that made you
They'll surely destroy you.
*/
#include <fstream>


#include <iostream>
using namespace std;



#include <fstream>


#include <vector>


#include <iterator>

#include <string>
#include <stdexcept>
#ifdef SPCPPL_DEBUG
	#define SPCPPL_ASSERT(condition) \
	if(!(condition)) { \
		throw std::runtime_error(std::string() + #condition + " in line " + std::to_string(__LINE__) + " in " + __PRETTY_FUNCTION__); \
	}
#else
#endif


#include <algorithm>


#define forn(i, n) for (int i = 0; i < int(n); i++)

#define el "\n";








//SWISTAKKK





#ifdef LOCAL
#define debug(x) {cerr <<#x<<" = " <<x<<"\n"; }
#define debug2(x, y) {cerr <<#x<<" = " <<x<<", "<<#y <<" = " <<y <<"\n";}
#define debug3(x, y, z) {cerr <<#x<<" = " <<x<<", "<<#y <<" = " <<y <<", "<<#z<<" = "<<z<<"\n";}
#define debug4(x, y, z, t) {cerr <<#x<<" = " <<x<<", "<<#y <<" = " <<y <<", "<<#z<<" = "<<z<<", "<<#t <<" = " <<t<<"\n";}
#define debugv(x) {{cerr <<#x <<" = "; FORE(itt, (x)) cerr <<*itt <<", "; cerr <<"\n"; }}
#else
#endif
#define make(type, x) type x; in>>x;
using namespace std;

template<class T1, class T2>
ostream& operator<< (ostream &out, std::pair<T1, T2> pair) { return out << "(" << pair.first << ", " << pair.second << ")";}

template<class T> void ResizeVec(T&, vector<int>) {}
template<class T> void ResizeVec(vector<T>& vec, vector<int> sz) {
    vec.resize(sz[0]); sz.erase(sz.begin()); if (sz.empty()) { return; }
    for (T& v : vec) { ResizeVec(v, sz); }
}









using namespace std;

class JamB {
public:
	void solve(std::istream& in, std::ostream& out) {
        make(int, tests);
        for(int test = 1; test <= tests; test++) {
            make(int, D);
            vector<int> a(D, 0);
            forn(i, D) in >> a[i];
            int res = 100000;
            for(int maxvalafter = 1; maxvalafter <= 1009; maxvalafter++) {
                int subtractions = 0;
                for(int i = 0; i < a.size(); i++) {
                    subtractions += a[i] / maxvalafter;
                    if (a[i] % maxvalafter == 0) subtractions--;
                }
                res = min(res, subtractions + maxvalafter);
            }
            out << "Case #" << test << ": " << res << el;
        }
	}
};


int main() {
	std::cin.sync_with_stdio(false);
	std::cin.tie(0);
	std::cout << std::fixed;
	std::cout.precision(20);
	JamB solver;
	std::istream& in(std::cin);
	std::ostream& out(std::cout);
	solver.solve(in, out);
	return 0;
}
