#include<stdio.h>
#include<algorithm>
int main()
{
	freopen("B-small-attempt3.in", "r", stdin);
	freopen("out.txt", "w", stdout);
	int t,i=1;
	scanf("%d",&t);
	while(i<=t)
	{
		int n,a[1001],j,min=0,min1[]={0,1,2,3,3,4,4,5,5,6},max,min2=0,min3=0,cond=1;
		scanf("%d",&n);
		for(j=0;j<n;j++)
		scanf("%d",&a[j]);
		std::sort(a,a+n);
		max=a[n-1];
		min=min1[max];
		if(max==9)
		{
			if(n>1)
			{
				if(a[n-2]<4)
				{
					min=5;
					cond=2;
				}
				else if(a[n-2]==6)
				{
					if(n>2)
					{
						if(a[n-3]<4)
						{
							min=6;
							cond=2;
						}
					}
					else
					{
						min=6;
						cond=2;
					}
				}
			}
			else
			{
				min=5;
				cond=2;
			}
		}
		if(cond==1)
		for(j=n-2;j>=0;j--)
		{
			if(a[j]>2)
			{
				if(max%2==1)
				{
					if(a[j]<=(max/2+1))
					{
						if(j<n-3)
						{
							min2=a[n-2]+1;
							min3=a[n-3]+2;
							if(min3<min2)
							min2=min3;
							if(min2<min)
							min=min2;
						}
						break;
					}
					else
					{
						if(j<n-3)
						{
							min2=a[n-2]+1;
							min3=a[n-3]+2;
						}
						min++;
						if(min2!=0&&(min2<=max||min3<=max))
						{
							if(min3<=min2)
							{
								min=min3;
								break;
							}
							else
							{
								min=min2;
								break;
							}
						}
					}
				}
				else
				{
					if(a[j]<=max/2)
					{
						if(j<n-3)
						{
							min2=a[n-2]+1;
							min3=a[n-3]+2;
							if(min3<min2)
							min2=min3;
							if(min2<min)
							min=min2;
						}
						break;
					}
					else
					{
						if(j<n-3)
						{
							min2=a[n-2]+1;
							min3=a[n-3]+2;
						}
						min++;
						if(min2!=0&&(min2<=max||min3<=max))
						{
							if(min3<=min2)
							{
								min=min3;
								break;
							}
							else
							{
								min=min2;
								break;
							}
						}
					}
				}
			}
			else
			{
				if(j<n-3)
				{
					min2=a[n-2]+1;
					min3=a[n-3]+2;
					if(min3<min2)
					min2=min3;
					if(min2<min)
					min=min2;
				}
				break;
			}
			if(min>max)
			{
				min=max;
				break;
			}
		}	
		if(n==3)
		{
			if(a[1]>=max/2+1&&a[0]>=max/2+1)
			{
			min2=a[n-2]+1;
			min3=a[n-3]+2;
			if(min3<min2)
			min2=min3;
			if(min2<min)
			min=min2;
			}
		}	
		printf("Case #%d: %d\n",i,min);
		i++;
	}
	return 0;
}
