#include<fstream.h>
#include<iostream.h>
#include<stdio.h>
#include<conio.h>
void main()
{
	 fstream fg("c:\\my2.txt",ios::in);
	 fstream fout("c:\\myout.txt",ios::out);
	 int t,i,h,w,map[10][10],j,k,tmp,side,link_map[10][10],tmp_j,tmp_k,min,n;
	 char basin[10][10],ch;
	 clrscr();
	 fg>>t;
	 for(i=0;i<t;i++)
	 {
	       fg>>h>>w;
	       for(j=0;j<h;j++)
	       {
		     for(k=0;k<w;k++)
		     {
			     fg>>tmp;
			     map[j][k]=tmp;
		     }
	       }
	       for(j=0;j<h;j++)
	       {
		      for(k=0;k<w;k++)
		      {
			    min=map[j][k];
			    side=-1;
			    if(j>0&&map[j-1][k]<min)
			    {                     //north
				    min=map[j-1][k];
				    side=(j-1)*w+k;
			    }
			    if(k>0&&map[j][k-1]<min)        //west
			    {
				    min=map[j][k-1];
				    side=j*w+k-1;
			    }
			    if(k<(w-1)&&map[j][k+1]<min)
			    {
				    min=map[j][k+1];
				    side=j*w+k+1;
			    }
			    if(j<(h-1)&&map[j+1][k]<min)
			    {
				     min=map[j+1][k];
				     side=(j+1)*w+k;
			    }
			    link_map[j][k]=side;
		      }
	       }
	       //look for a
	       for(j=0;j<h;j++)
	       {
		    for(k=0;k<w;k++)
		    {
			  basin[j][k]='z';
		    }
	       }
	       ch='a';
	       tmp=link_map[0][0];
	       j=0;
	       k=0;
	       while(tmp!=-1)
	       {
		    j=tmp/w;
		    k=tmp%w;
		    tmp=link_map[j][k];
	       }
	       basin[j][k]=ch;
	       ch=ch+1;
	       for(j=0;j<h;j++)
	       {
		     for(k=0;k<w;k++)
		     {
			    if(link_map[j][k]==-1&&basin[j][k]!='a')
			    {
				     basin[j][k]=ch;
				     ch=ch+1;
			    }
		     }
	       }
	       for(j=0;j<h;j++)
	       {
		     for(k=0;k<w;k++)
		     {
			    if(link_map[j][k]!=-1)
			    {
				    tmp=link_map[j][k];
				    while(tmp!=-1)
				    {
					   tmp_j=tmp/w;
					   tmp_k=tmp%w;
					   tmp=link_map[tmp_j][tmp_k];
				    }
				    basin[j][k]=basin[tmp_j][tmp_k];
			    }
		     }
	       }
	       fout<<"Case #"<<(i+1)<<":"<<endl;
	       for(j=0;j<h;j++)
	       {
		  for(k=0;k<w;k++)
		  {
		       fout<<basin[j][k]<<" ";
		  }
		  fout<<endl;
	       }
	       //getch();
	 }
	 getch();
}