filename = 'B-large.in'

f = open(filename, 'r')
num_cases = int(f.readline())

class Case:
    pass
    
def next_case(f):
    line = f.readline()
    if line == '':
        return []

    nums = line.split()
    c = Case()
    c.C = float(nums[0])    # cost of cookie farm
    c.F = float(nums[1])    # additional cookies generated by a farm
    c.X = float(nums[2])    # winning cookie amount
    return c

def find_ans_str(c):
    rate = 2   # 2 per sec
    time_elapsed = 0

    # once it takes less time to wait until X is reached than it takes to buy another farm
    # and then wait until X is reached, the optimal solution is found.

    while True:
        # buy farm or wait until victory test
        time_no_farm = c.X / rate
        time_with_farm = c.C / rate + c.X / (rate + c.F)
        if time_no_farm <= time_with_farm:
            return '{:.7f}'.format(time_elapsed + time_no_farm)
        else:
            # buy farm
            time_until_next_farm = c.C / rate
            time_elapsed += time_until_next_farm
            rate += c.F
        
c = next_case(f)
casenum = 1
while c != []:

    ans_str = 'Case #' + str(casenum) + ': '
    ans_str += find_ans_str(c)
    print(ans_str)
    c = next_case(f)
    casenum += 1

if casenum - 1 != num_cases:
    print('error: not all cases read')
f.close()
