#include<bits/stdc++.h>
using namespace std;
int main()
{
    ifstream cin("a.txt");
    ofstream cout("b.txt");
    int t,var=0,i,n,m,ind=0,cnt;
    cin>>t;
    while(t--)
    {
        ind=0;
        var++;
        cout<<"Case #"<<var<<": ";
        string str;
        cin>>str;
        n=str.size();
        m=n/3+1;
        int ar[27],ans[1000];
        memset(ar,0,sizeof(ar));
        for(i=0;i<n;i++)
            ar[str[i]-'A'+1]++;
        if(ar[26])
        {
            cnt=ar[26];
            ar[26]=0;
            ar[5]-=cnt;
            ar[18]-=cnt;
            ar[15]-=cnt;
            while(cnt--)
                ans[ind++]=0;
        }
        if(ar[21])
        {
            cnt=ar[21];
            ar[21]=0;
            ar[6]-=cnt;
            ar[15]-=cnt;
            ar[18]-=cnt;
            while(cnt--)
                ans[ind++]=4;
        }
        if(ar[23])
        {
            cnt=ar[23];
            ar[23]=0;
            ar[20]-=cnt;
            ar[15]-=cnt;
            while(cnt--)
                ans[ind++]=2;
        }
        if(ar[15])
        {
            cnt=ar[15];
            ar[15]=0;
            ar[5]-=cnt;
            ar[14]-=cnt;
            while(cnt--)
                ans[ind++]=1;
        }
        if(ar[18])
        {
            cnt=ar[18];
            ar[18]=0;
            ar[20]-=cnt;
            ar[8]-=cnt;
            ar[5]-=(cnt+cnt);
            while(cnt--)
                ans[ind++]=3;
        }
        if(ar[8])
        {
            cnt=ar[8];
            ar[8]=0;
            ar[9]-=cnt;
            ar[7]-=cnt;
            ar[20]-=cnt;
            ar[5]-=cnt;
            while(cnt--)
                ans[ind++]=8;
        }
        if(ar[24])
        {
            cnt=ar[24];
            ar[24]=0;
            ar[19]-=cnt;
            ar[9]-=cnt;
            while(cnt--)
                ans[ind++]=6;
        }
        if(ar[19])
        {
            cnt=ar[19];
            ar[19]=0;
            ar[22]-=cnt;
            ar[14]-=cnt;
            ar[5]-=cnt+cnt;
            while(cnt--)
                ans[ind++]=7;
        }
        if(ar[22])
        {
            cnt=ar[22];
            ar[22]=0;
            ar[6]-=cnt;
            ar[5]-=cnt;
            ar[9]-=cnt;
            while(cnt--)
                ans[ind++]=5;
        }
        if(ar[14])
        {
            cnt=ar[14]/2;
            ar[14]=0;
            ar[5]-=cnt;
            ar[9]-=cnt;
            while(cnt--)
                ans[ind++]=9;
        }
        sort(ans,ans+ind);
        for(i=0;i<ind;i++)
            cout<<ans[i];
        cout<<'\n';
    }
}
