#include<iostream>
#include<cstdio>
#include<algorithm>
#include<vector>
using namespace std;
int main()
{
	freopen("A-large.in","r",stdin);
	freopen("output.txt","w",stdout);
	int t;
	cin>>t;
	for(int cno=1;cno<=t;cno++)
	{
		char s[2001];
		cin>>s;
		int a[26]={0},i=0;
		while(s[i])
		{
			a[s[i]-'A']++;
			i++;
		}
		int ans[2000],l=0;
		while(a['Z'-'A'])
		{
			ans[l++]=0;
			a['Z'-'A']--;
			a['E'-'A']--;
			a['R'-'A']--;
			a['O'-'A']--;
		}
		while(a['W'-'A'])
		{
			ans[l++]=2;
			a['T'-'A']--;
			a['W'-'A']--;
			a['O'-'A']--;
		}
		while(a['U'-'A'])
		{
			ans[l++]=4;
			a['F'-'A']--;
			a['O'-'A']--;
			a['U'-'A']--;
			a['R'-'A']--;
		}
		while(a['G'-'A'])
		{
			ans[l++]=8;
			a['E'-'A']--;
			a['I'-'A']--;
			a['G'-'A']--;
			a['H'-'A']--;
			a['T'-'A']--;
		}
		while(a['X'-'A'])
		{
			ans[l++]=6;
			a['S'-'A']--;
			a['I'-'A']--;
			a['X'-'A']--;
		}
		while(a['S'-'A'])
		{
			ans[l++]=7;
			a['S'-'A']--;
			a['E'-'A']--;
			a['V'-'A']--;
			a['E'-'A']--;
			a['N'-'A']--;
		}
		while(a['O'-'A'])
		{
			ans[l++]=1;
			a['O'-'A']--;
			a['N'-'A']--;
			a['E'-'A']--;
		}
		while(a['R'-'A'])
		{
			ans[l++]=3;
			a['T'-'A']--;
			a['H'-'A']--;
			a['R'-'A']--;
			a['E'-'A']--;
			a['E'-'A']--;
		}
		while(a['V'-'A'])
		{
			ans[l++]=5;
			a['F'-'A']--;
			a['I'-'A']--;
			a['V'-'A']--;
			a['E'-'A']--;
		}
		while(a['I'-'A'])
		{
			ans[l++]=9;
			a['N'-'A']--;
			a['I'-'A']--;
			a['N'-'A']--;
			a['E'-'A']--;
		}
		sort(ans,ans+l);
		cout<<"Case #"<<cno<<": ";
		for(i=0;i<l;i++)
		{
			cout<<ans[i];
		}
		cout<<endl;
	}
	return 0;
}
