#include<iostream>
#include<stdio.h>
using namespace std;
int main()
{
    int t,i,a[10],c[30],k;
    char s[2001];
    //freopen("A-large.in","r",stdin);
    //freopen("outdiglarge.txt","w",stdout);
    cin>>t;
    for(k=1;k<=t;k++)
    {
        for(i=0;i<10;i++)
            a[i]=0;
        for(i=0;i<30;i++)
            c[i]=0;
        cin>>s;
        for(i=0;s[i]!='\0';i++)
            c[s[i]-'A']++;
        a[0]=c['Z'-'A'];
        c['Z'-'A']-=a[0];
        c['E'-'A']-=a[0];
        c['R'-'A']-=a[0];
        c['O'-'A']-=a[0];
        a[2]=c['W'-'A'];
        c['T'-'A']-=a[2];
        c['W'-'A']-=a[2];
        c['O'-'A']-=a[2];
        a[4]=c['U'-'A'];
        c['F'-'A']-=a[4];
        c['O'-'A']-=a[4];
        c['U'-'A']-=a[4];
        c['R'-'A']-=a[4];
        a[6]=c['X'-'A'];
        c['S'-'A']-=a[6];
        c['I'-'A']-=a[6];
        c['X'-'A']-=a[6];
        a[8]=c['G'-'A'];
        c['E'-'A']-=a[8];
        c['I'-'A']-=a[8];
        c['G'-'A']-=a[8];
        c['H'-'A']-=a[8];
        c['T'-'A']-=a[8];
        a[1]=c['O'-'A'];
        c['O'-'A']-=a[1];
        c['N'-'A']-=a[1];
        c['E'-'A']-=a[1];
        a[3]=c['R'-'A'];
        c['T'-'A']-=a[3];
        c['H'-'A']-=a[3];
        c['R'-'A']-=a[3];
        c['E'-'A']-=a[3];
        c['E'-'A']-=a[3];
        a[5]=c['F'-'A'];
        c['F'-'A']-=a[5];
        c['I'-'A']-=a[5];
        c['V'-'A']-=a[5];
        c['E'-'A']-=a[5];
        a[7]=c['S'-'A'];
        c['S'-'A']-=a[7];
        c['E'-'A']-=a[7];
        c['V'-'A']-=a[7];
        c['E'-'A']-=a[7];
        c['N'-'A']-=a[7];
        a[9]=c['I'-'A'];
        cout<<"Case #"<<k<<": ";
        for(i=0;i<10;i++)
        {
            while(a[i]--)
                cout<<i;
        }
        cout<<endl;
    }
    return 0;
}
