#include<bits/stdc++.h>

int main()
{
	int t,i,j,k,n,p,u,T,m;
	char c[1000000],e;
	scanf("%d",&t);
	for(T=1;T<=t;++T)
	{
		int a[30]={0};
		int b[10]={0};
		scanf("%s",c);
		n=strlen(c);
		printf("Case #%d: ",T);
		for(i=0;i<n;++i)
		{
			a[c[i]-'A']++;
		}
		if(a['Z'-'A'])
		{
			a['E'-'A']-=a['Z'-'A'];
			a['R'-'A']-=a['Z'-'A'];
			a['O'-'A']-=a['Z'-'A'];
			b[0]=a['Z'-'A'];
			a['Z'-'A']=0;
		}
		if(a['W'-'A'])
		{
			a['T'-'A']-=a['W'-'A'];
			a['O'-'A']-=a['W'-'A'];
			b[2]=a['W'-'A'];
			a['W'-'A']=0;
		}
		if(a['U'-'A'])
		{
			a['F'-'A']-=a['U'-'A'];
			a['O'-'A']-=a['U'-'A'];
			a['R'-'A']-=a['U'-'A'];
			b[4]=a['U'-'A'];
			a['U'-'A']=0;
		}
		if(a['X'-'A'])
		{
			a['I'-'A']-=a['X'-'A'];
			a['S'-'A']-=a['X'-'A'];
			b[6]=a['X'-'A'];
			a['X'-'A']=0;
		}
		if(a['G'-'A'])
		{
			a['E'-'A']-=a['G'-'A'];
			a['I'-'A']-=a['G'-'A'];
			a['H'-'A']-=a['G'-'A'];
			a['T'-'A']-=a['G'-'A'];
			b[8]=a['G'-'A'];
			a['G'-'A']=0;
		}
		if(a['O'-'A'])
		{
			a['N'-'A']-=a['O'-'A'];
			a['E'-'A']-=a['O'-'A'];
			b[1]=a['O'-'A'];
			a['O'-'A']=0;
		}
		if(a['T'-'A'])
		{
			a['H'-'A']-=a['T'-'A'];
			a['R'-'A']-=a['T'-'A'];
			a['E'-'A']-=a['T'-'A'];
			a['E'-'A']-=a['T'-'A'];
			b[3]=a['T'-'A'];
			a['T'-'A']=0;
		}
		if(a['F'-'A'])
		{
			a['I'-'A']-=a['F'-'A'];
			a['V'-'A']-=a['F'-'A'];
			a['E'-'A']-=a['F'-'A'];
			b[5]=a['F'-'A'];
			a['F'-'A']=0;
		}
		if(a['S'-'A'])
		{
			b[7]=a['S'-'A'];			
		}
		if(a['I'-'A'])
		{
			b[9]=a['I'-'A'];
		}
		for(i=0;i<10;++i)
		{
			while(b[i]--)
				printf("%d",i);
		}
		printf("\n");
	}
	return 0;
}
