#include <bits/stdc++.h>
using namespace std;
int main()
{
    cout.tie(0);
    std::ios::sync_with_stdio(false);
    ifstream fin;
    fin.open("A-largeB.in",ios::in);
    ofstream fout;
    fout.open("output.txt",ios::out);
    int t,T;
    fin>>T;
    for(t=1;t<=T;t++)
    {
        long long i=0;
        map<char,int> m;
        string s,ans="";
        fin>>s;
        for(i=65;i<=97;i++)
            m[(char)i]=0;
        for(i=0;i<s.size();i++)
            m[s[i]]++;
        if(m['Z']>0)
        {
            for(i=0;i<m['Z'];i++)
            {
                ans=ans+"0";   
            }
            m['E']-=m['Z'];
            m['R']-=m['Z'];
            m['O']-=m['Z'];
            m['Z']=0;
        }
        if(m['W']>0)
        {
            for(i=0;i<m['W'];i++)
            {
                ans=ans+"2";   
            }
            m['T']-=m['W'];
            m['O']-=m['W'];
            m['W']=0;
        }
        if(m['U']>0)
        {
            for(i=0;i<m['U'];i++)
            {
                ans=ans+"4";   
            }
            m['F']-=m['U'];
            m['O']-=m['U'];
            m['R']-=m['U'];
            m['U']=0;
        }
        if(m['X']>0)
        {
            for(i=0;i<m['X'];i++)
            {
                ans=ans+"6";   
            }
            m['S']-=m['X'];
            m['I']-=m['X'];
            m['X']=0;
        } 
        if(m['G']>0)
        {
            for(i=0;i<m['G'];i++)
            {
                ans=ans+"8";   
            }
            m['E']-=m['G'];
            m['I']-=m['G'];
            m['H']-=m['G'];
            m['T']-=m['G'];
            m['G']=0;
        }
        if(m['O']>0)
        {
            for(i=0;i<m['O'];i++)
            {
                ans=ans+"1";   
            }
            m['E']-=m['O'];
            m['N']-=m['O'];
            m['O']=0;
        }
        if(m['R']>0)
        {
            for(i=0;i<m['R'];i++)
            {
                ans=ans+"3";   
            }
            m['T']-=m['R'];
            m['H']-=m['R'];
            m['E']-=m['R'];
            m['E']-=m['R'];
            m['R']=0;
        }
        if(m['S']>0)
        {
            for(i=0;i<m['S'];i++)
            {
                ans=ans+"7";   
            }
            m['E']-=m['S'];
            m['V']-=m['S'];
            m['E']-=m['S'];
            m['N']-=m['S'];
            m['S']=0;
        }
        if(m['F']>0)
        {
            for(i=0;i<m['F'];i++)
            {
                ans=ans+"5";   
            }
            m['E']-=m['F'];
            m['I']-=m['F'];
            m['V']-=m['F'];
            m['F']=0;
        }
        if(m['I']>0)
        {
            for(i=0;i<m['I'];i++)
            {
                ans=ans+"9";   
            }
            m['E']-=m['I'];
            m['N']-=m['I'];
            m['N']-=m['I'];
            m['I']=0;
        }
        sort(ans.begin(),ans.end());
        fout<<"Case #"<<t<<": "<<ans<<endl;
    }
    return 0;
}