#include<iostream>
using namespace std;
int main()
{
	int data[50];
	char asd[3000];
	int out[10];
	int i,j,k,l,n;
	cin>>n;
	for(i=0;i<n;i++)
    {
        cin>>asd;
        for(j=0;j<30;j++)
        {
            data[j]=0;
        }
        for(j=0;j<10;j++)
        {
            out[j]=0;
        }
        for(j=0;asd[j]!='\0';j++)
        {
            data[asd[j]-'A']++;
        }
        while(data['Z'-'A'])///00000
        {
            data['Z'-'A']--;
            data['E'-'A']--;
            data['R'-'A']--;
            data['O'-'A']--;
            out[0]++;
        }
        while(data['U'-'A'])///44444444444444
        {
            data['U'-'A']--;
            data['F'-'A']--;
            data['O'-'A']--;
            data['R'-'A']--;
            out[4]++;
        }
        while(data['W'-'A'])///22222222222
        {
            data['T'-'A']--;
            data['W'-'A']--;
            data['O'-'A']--;
            out[2]++;
        }
        while(data['X'-'A'])///666666666666
        {
            data['S'-'A']--;
            data['I'-'A']--;
            data['X'-'A']--;
            out[6]++;
        }
        while(data['S'-'A'])///7777777
        {
            data['S'-'A']--;
            data['E'-'A']--;
            data['V'-'A']--;
            data['E'-'A']--;
            data['N'-'A']--;
            out[7]++;
        }
        while(data['V'-'A'])///5555
        {
            data['F'-'A']--;
            data['I'-'A']--;
            data['V'-'A']--;
            data['E'-'A']--;
            out[5]++;
        }
        while(data['R'-'A'])///3
        {
            data['T'-'A']--;
            data['H'-'A']--;
            data['R'-'A']--;
            data['E'-'A']--;
            data['E'-'A']--;
            out[3]++;
        }
        while(data['O'-'A'])///1
        {
            data['O'-'A']--;
            data['N'-'A']--;
            data['E'-'A']--;
            out[1]++;
        }
        while(data['N'-'A'])///9
        {
            data['N'-'A']--;
            data['I'-'A']--;
            data['N'-'A']--;
            data['E'-'A']--;
            out[9]++;
        }
        while(data['E'-'A'])///9
        {
            data['E'-'A']--;
            data['I'-'A']--;
            data['G'-'A']--;
            data['H'-'A']--;

            data['T'-'A']--;
            out[8]++;
        }

        cout<<"Case #"<<i+1<<": ";
        for(j=0;j<10;j++)
        {
            while(out[j])
            {
                cout<<j;
                out[j]--;
            }
        }
        cout<<endl;
    }
}
