#include<iostream>
#include<math.h>
#include<string.h>
using namespace std;
int main()
{
    int i,j,k,t,c;
    char s[2001];
    int fre[26]={0};
    int num[10]={0};
    cin>>t;
    for(j=0;j<t;j++)
    {
        i=0;
        for(i=0;i<26;i++)
        {
            fre[i]=0;
        }
        for(i=0;i<10;i++)
        {
            num[i]=0;
        }
        cout<<"Case #"<<j+1<<": ";
        cin>>s;
        for(i=0;s[i]!=0;i++)
        {
            fre[s[i]-'A']++;
        }
        k=fre['X'-'A'];
        if(k)
        {
            num[6]=k;
            fre['S'-'A']-=k;
            fre['X'-'A']-=k;
            fre['I'-'A']-=k;
        }
        k=fre['S'-'A'];
        if(k)
        {
            num[7]=k;
            fre['S'-'A']-=k;
            fre['E'-'A']-=k;
            fre['V'-'A']-=k;
            fre['E'-'A']-=k;
            fre['N'-'A']-=k;
        }
        k=fre['V'-'A'];
        if(k)
        {
            num[5]=k;
            fre['F'-'A']-=k;
            fre['I'-'A']-=k;
            fre['V'-'A']-=k;
            fre['E'-'A']-=k;
        }
        k=fre['Z'-'A'];
        if(k)
        {
            num[0]=k;
            fre['Z'-'A']-=k;
            fre['E'-'A']-=k;
            fre['R'-'A']-=k;
            fre['O'-'A']-=k;
        }
        k=fre['W'-'A'];
        if(k)
        {
            num[2]=k;
            fre['T'-'A']-=k;
            fre['W'-'A']-=k;
            fre['O'-'A']-=k;
        }
        k=fre['F'-'A'];
        if(k)
        {
            num[4]=k;
            fre['F'-'A']-=k;
            fre['O'-'A']-=k;
            fre['U'-'A']-=k;
            fre['R'-'A']-=k;
        }
        k=fre['O'-'A'];
        if(k)
        {
            num[1]=k;
            fre['O'-'A']-=k;
            fre['N'-'A']-=k;
            fre['E'-'A']-=k;
        }
        k=fre['R'-'A'];
        if(k)
        {
            num[3]=k;
            fre['T'-'A']-=k;
            fre['H'-'A']-=k;
            fre['R'-'A']-=k;
            fre['E'-'A']-=k;
            fre['E'-'A']-=k;
        }
        k=fre['N'-'A'];
        k/=2;
        if(k)
        {
            num[9]=k;
            fre['N'-'A']-=k;
            fre['I'-'A']-=k;
            fre['N'-'A']-=k;
            fre['E'-'A']-=k;
        }
        k=fre['E'-'A'];
        if(k)
        {
            num[8]=k;
            fre['E'-'A']-=k;
            fre['I'-'A']-=k;
            fre['G'-'A']-=k;
            fre['H'-'A']-=k;
            fre['T'-'A']-=k;
        }
        for(i=0;i<10;i++)
        {
            for(k=0;k<num[i];k++)
            {

                cout<<i;
            }
        }
        if(j!=t-1)
        {
            cout<<"\n";
        }
    }
    return 0;
}
