#include<bits/stdc++.h>
using namespace std;
int main()
{
    int a[120],t,c,i,j,d[1000];
    char s[2500];
    cin>>t;
    for(c=1;c<=t;c++)
    {
        memset(a,0,sizeof(a));
        memset(d,-1,sizeof(d));
        cin>>s;
        j=0;
        for(i=0;i<strlen(s);i++)
        {
            a[s[i]]++;
        }
        while(a['S']&&a['I']&&a['X'])
        {
            d[j]=6;
            j++;
            a['S']--;
            a['I']--;
            a['X']--;
        }
        while(a['T']&&a['W']&&a['O'])
        {
            d[j]=2;
            j++;
            a['T']--;
            a['W']--;
            a['O']--;
        }
        while(a['F']&&a['O']&&a['U']&&(a['R']))
        {
            d[j]=4;
            j++;
            a['F']--;
            a['O']--;
            a['U']--;
            a['R']--;
        }
        while(a['E']&&a['I']&&a['G']&&(a['H'])&&a['T'])
        {
            d[j]=8;
            j++;
            a['E']--;
            a['I']--;
            a['G']--;
            a['H']--;
            a['T']--;
        }
        while(a['T']&&a['H']&&a['R']&&(a['E']>=2))
        {
            d[j]=3;
            j++;
            a['T']--;
            a['H']--;
            a['R']--;
            a['E']-=2;
        }
        while((a['Z'])&&a['E']&&a['R']&&a['O'])
        {
            d[j]=0;
            j++;
            a['Z']--;
            a['E']--;
            a['R']--;
            a['O']--;
        }
        while(a['O']&&a['N']&&a['E'])
        {
            d[j]=1;
            j++;
            a['O']--;
            a['N']--;
            a['E']--;
        }
        while(a['F']&&a['I']&&a['V']&&(a['E']))
        {
            d[j]=5;
            j++;
            a['F']--;
            a['I']--;
            a['V']--;
            a['E']--;
        }
        while(a['S']&&a['V']&&a['N']&&(a['E']>=2))
        {
            d[j]=7;
            j++;
            a['S']--;
            a['V']--;
            a['N']--;
            a['E']-=2;
        }
        while(a['E']&&a['I']&&(a['N']>=2))
        {
            d[j]=9;
            j++;
            a['I']--;
            a['E']--;
            a['N']-=2;
        }
        sort(d,d+j);
        if(a['S']||a['I']||a['X']||a['N']||a['E']||a['V']||a['Z']||a['F'])
        {
            cout<<"error";
            continue;
        }
        cout<<"Case #"<<c<<": ";
        for(i=0;i<j;i++)
        {
            cout<<d[i];
        }
        cout<<endl;
    }
    return 0;
}
