#include<stdio.h>
#include<string.h>
main()
{
	//freopen("A-large (2).in","r",stdin);
	//freopen("output_file2.out","w",stdout);
	int t,ca=0,l,i,j;
	char s[2000];
	int ans[10],a[26];
	scanf("%d",&t);
	while(t--)
	{
		ca++;
		scanf("%s",&s);
		l=strlen(s);
		for(i=0;i<26;i++)
		{
			a[i]=0;
			if(i<10)
			{
				ans[i]=0;
			}
		}
		i=0;
		while(s[i]!='\0')
		{
			j=s[i]-'A';
			a[j]++;
			i++;
		}
	/*	for(i=0;i<26;i++)
		{
			printf(" %d:%d ",i,a[i]);
		}*/
		if(a['Z'-'A']!=0)
		{
			while(a['Z'-'A']!=0)
			{
				a['Z'-'A']--;
				a['E'-'A']--;
				a['R'-'A']--;
				a['O'-'A']--;
				ans[0]++;
				//printf("0done");
			}
		}
		if(a['W'-'A']!=0)
		{
			while(a['W'-'A']!=0)
			{
				a['T'-'A']--;
				a['W'-'A']--;
				a['O'-'A']--;
				ans[2]++;
			}
		}
		
		if(a['U'-'A']!=0)
		{
			while(a['U'-'A']!=0)
			{
				a['F'-'A']--;
				a['O'-'A']--;
				a['R'-'A']--;
				a['U'-'A']--;
				ans[4]++;
			}
		}
		if(a['X'-'A']!=0)
		{
			while(a['X'-'A']!=0)
			{
				a['S'-'A']--;
				a['I'-'A']--;
				a['X'-'A']--;
				ans[6]++;
			}
		}
		if(a['S'-'A']!=0)
		{
			while(a['S'-'A']!=0)
			{
				a['S'-'A']--;
				a['E'-'A']--;
				a['V'-'A']--;
				a['E'-'A']--;
				a['N'-'A']--;
				ans[7]++;
			}
		}
		if(a['G'-'A']!=0)
		{
			while(a['G'-'A']!=0)
			{
				a['T'-'A']--;
				a['I'-'A']--;
				a['G'-'A']--;
				a['E'-'A']--;
				a['H'-'A']--;
				ans[8]++;
			}
		}
		if(a['H'-'A']!=0)
		{
			while(a['H'-'A']!=0)
			{
				a['T'-'A']--;
				a['H'-'A']--;
				a['R'-'A']--;
				a['E'-'A']--;
				a['E'-'A']--;
				ans[3]++;
			}
		}
	    if(a['O'-'A']!=0)
		{
			while(a['O'-'A']!=0)
			{
				a['O'-'A']--;
				a['N'-'A']--;
				a['E'-'A']--;
				ans[1]++;
			}
		}
		if(a['F'-'A']!=0)
		{
			while(a['F'-'A']!=0)
			{
				a['F'-'A']--;
				a['I'-'A']--;
				a['V'-'A']--;
				a['E'-'A']--;
				ans[5]++;
			}
		}
		if(a['E'-'A']!=0)
		{
			while(a['E'-'A']!=0)
			{
				a['N'-'A']--;
				a['I'-'A']--;
				a['N'-'A']--;
				a['E'-'A']--;
				ans[9]++;
			}
		}
		
		/*for(i=0;i<10;i++)
		{
			
				printf("%d",ans[i]);
			
		}*/
		printf("Case #%d: ",ca);
		
		for(i=0;i<10;i++)
		{
			while(ans[i]!=0)
			{
				printf("%d",i);
				ans[i]--;
			}
		}
		printf("\n");
	}
	return 0;
}
