/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author
 */

#include <iostream>
#include <fstream>

#include <iostream>

using namespace std;

class TaskB {
public:
    void solve(istream &in, ostream &out) {
        int T;
        in >> T;
        for (int t = 0; t < T; ++t) {
            string s;
            in >> s;
            int turns = 0;
            for (int i = s.size() - 1; i >= 0; i--) {
                if (s[i] == '-') {
                    turns++;
                    transform(s.begin(), s.begin() + i + 1, s.begin(), [](char c) {
                        return c == '-' ? '+' : '-';
                    });
                }
            }
            out << "Case #" << t + 1 << ": " << turns << endl;
        }
    }
};

#include <dirent.h>
#include <stdexcept>
#include <regex>
#include <sys/stat.h>
#include <cstdint>

std::string getLastFileName(const std::string &regexString) {
    DIR *dir;
    dirent *entry;
    std::string result = "";
    int64_t resultModificationTime = 0;
    std::regex regex(regexString);
    if ((dir = opendir(".")) != NULL) {
        while ((entry = readdir(dir)) != NULL) {
            if (std::regex_match(entry->d_name, regex)) {
                struct stat buffer;
                stat(entry->d_name, &buffer);
                int64_t modificationTime = static_cast<int64_t>(buffer.st_mtimespec.tv_sec) * 1000000000 +
                                           static_cast<int64_t>(buffer.st_mtimespec.tv_nsec);

                if (modificationTime > resultModificationTime) {
                    resultModificationTime = modificationTime;
                    result = entry->d_name;
                }
            }
        }
        closedir(dir);
    } else {
        throw std::runtime_error("Couldn't open current directory");
    }
    if (result.empty()) {
        throw std::runtime_error("No file found");
    }
    return result;
}

int main() {
    TaskB solver;
    std::ifstream in(getLastFileName("B-(small|large).*[.]in"));
    std::ofstream out("b.out");
    solver.solve(in, out);
    return 0;
}
