

#define QUANT_ARGC 2
#define ARGV_INPUT_FILE_POS 1
#define FIRST_INPUT_LINE 0
#define QUANT_HEADER_LINES 1

#define INPUT_FILENAME_EXTENSION ".in"
#define OUTPUT_FILENAME_EXTENSION ".out"

#define INSOMNIA_STR "INSOMNIA"
