SET(ProjectName code_jam)
PROJECT(${ProjectName})


CMAKE_MINIMUM_REQUIRED(VERSION 2.6)

FIND_PACKAGE(OpenMP) 
if (OPENMP_FOUND) 
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
endif (OPENMP_FOUND)

IF(UNIX)
#support of ARRAY<T,N>
SET(CMAKE_CXX_FLAGS "-std=c++0x")
ENDIF(UNIX)

ADD_DEFINITIONS(-DTHIS_SOURCE_DIR="${CMAKE_CURRENT_SOURCE_DIR}")


INCLUDE_DIRECTORIES(

)

ADD_EXECUTABLE(${ProjectName} jam_d.cpp)
