T=int(input())
for x in range(T):
    varInput=str(input())
    splitInput=list(varInput)
    num=[]
    for i in range(0,len(splitInput)):
        if splitInput[i]=='Z':
            splitInput.insert(splitInput.index('Z'),'0')
            splitInput.remove('Z')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            splitInput.insert(splitInput.index('R'),'0')
            splitInput.remove('R')
            splitInput.insert(splitInput.index('O'),'0')
            splitInput.remove('O')
            num.append('0')
        if splitInput[i]=='W':
            splitInput.insert(splitInput.index('T'),'0')
            splitInput.remove('T')
            splitInput.insert(splitInput.index('W'),'0')
            splitInput.remove('W')
            splitInput.insert(splitInput.index('O'),'0')
            splitInput.remove('O')
            num.append('2')
        if splitInput[i]=='U':
            splitInput.insert(splitInput.index('F'),'0')
            splitInput.remove('F')
            splitInput.insert(splitInput.index('O'),'0')
            splitInput.remove('O')
            splitInput.insert(splitInput.index('U'),'0')
            splitInput.remove('U')
            splitInput.insert(splitInput.index('R'),'0')
            splitInput.remove('R')
            num.append('4')
        if splitInput[i]=='X':
            splitInput.insert(splitInput.index('S'),'0')
            splitInput.remove('S')
            splitInput.insert(splitInput.index('I'),'0')
            splitInput.remove('I')
            splitInput.insert(splitInput.index('X'),'0')
            splitInput.remove('X')
            num.append('6')
        if splitInput[i]=='G':
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            splitInput.insert(splitInput.index('I'),'0')
            splitInput.remove('I')
            splitInput.insert(splitInput.index('G'),'0')
            splitInput.remove('G')
            splitInput.insert(splitInput.index('H'),'0')
            splitInput.remove('H')
            splitInput.insert(splitInput.index('T'),'0')
            splitInput.remove('T')
            num.append('8')
    for i in range(0,len(splitInput)):
        if splitInput[i]=='O':
            splitInput.insert(splitInput.index('O'),'0')
            splitInput.remove('O')
            splitInput.insert(splitInput.index('N'),'0')
            splitInput.remove('N')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            num.append('1')
        if splitInput[i]=='T':
            splitInput.insert(splitInput.index('T'),'0')
            splitInput.remove('T')
            splitInput.insert(splitInput.index('H'),'0')
            splitInput.remove('H')
            splitInput.insert(splitInput.index('R'),'0')
            splitInput.remove('R')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            num.append('3')
        if splitInput[i]=='F':
            splitInput.insert(splitInput.index('F'),'0')
            splitInput.remove('F')
            splitInput.insert(splitInput.index('I'),'0')
            splitInput.remove('I')
            splitInput.insert(splitInput.index('V'),'0')
            splitInput.remove('V')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            num.append('5')
        if splitInput[i]=='S':
            splitInput.insert(splitInput.index('S'),'0')
            splitInput.remove('S')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            splitInput.insert(splitInput.index('V'),'0')
            splitInput.remove('V')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            splitInput.insert(splitInput.index('N'),'0')
            splitInput.remove('N')
            num.append('7')
    for i in range(0,len(splitInput)):
        if splitInput[i]=='N':
            splitInput.insert(splitInput.index('N'),'0')
            splitInput.remove('N')
            splitInput.insert(splitInput.index('I'),'0')
            splitInput.remove('I')
            splitInput.insert(splitInput.index('N'),'0')
            splitInput.remove('N')
            splitInput.insert(splitInput.index('E'),'0')
            splitInput.remove('E')
            num.append('9')
    num.sort()
    num = ''.join(num)
    print("Case #"+str(x+1)+":",num)