#include <iostream>
#include <fstream>
#include <stdio.h>
using namespace std;
int main()
{
    ofstream fout("c:\\me4.txt");
    int i,num,times,j,k,l,m,line,row,mines,selecter,mode;//mode is 1:vertical 2:horizonal
    int temp2,temp3,temp4,temp5,linetemp,temper,flag;
    cin>>num;
    char paint[5][5];
    for(i=0;i<5;i++)
    for(j=0;j<5;j++)
    paint[i][j]='*';
    for(i=0;i<num;i++)
    {
        cin>>line>>row>>mines;
        fout<<"Case #"<<i+1<<":"<<endl;
        if(line>=row){selecter=row;times=line;mode=1;}
        else {selecter=line;times=row;mode=2;}
        if(selecter==1)
        {
            if(mode==1)
            {
                if(mines==line)
                {
                    fout<<"Impossible"<<endl;
                    continue;
                }
                for(j=1;j<line-mines;j++)
                {
                    paint[j][0]='.';
                }
                fout<<"c"<<endl;
                for(j=1;j<line;j++)
                {
                    fout<<paint[j][0]<<endl;
                }
            }
            if(mode==2)
            {
                if(mines==row)
                {
                    fout<<"Impossible"<<endl;
                    continue;
                }
                for(j=1;j<row-mines;j++)
                {
                    paint[0][j]='.';
                }
                fout<<"c";
                for(j=1;j<row;j++)
                {
                    fout<<paint[0][j];
                }
                fout<<endl;
            }

        }
        if(selecter==2)
        {

            if(mines==1)
            {

                fout<<"Impossible"<<endl;
                continue;
            }
            else if(mines==selecter*times-1)
            {
                for(j=0;j<selecter;j++)
                for(k=0;k<times;k++)
                {
                    paint[j][k]='*';
                }
                paint[0][0]='c';
            }
            else if(mines%2!=0||mines==selecter*times-2)
            {
                fout<<"Impossible"<<endl;
                continue;
            }

            else
            {
                for(j=0;j<selecter;j++)
                for(k=0;k<times;k++)
                {
                    paint[j][k]='*';
                }

                for(j=0;j<selecter;j++)
                for(k=0;k<(selecter*times-mines)/2;k++)
                {
                    paint[j][k]='.';
                }
                paint[0][0]='c';
            }
            if(mode==2)
            {
                for(j=0;j<selecter;j++)
                {
                for(k=0;k<times;k++)
                {
                    fout<<paint[j][k];
                }
                fout<<endl;
                }
            }
            if(mode==1)
            {
                for(j=0;j<times;j++)
                {
                for(k=0;k<selecter;k++)
                {
                    fout<<paint[k][j];
                }
                fout<<endl;
                }
            }
        }
        if(selecter==3)
        {
            flag=0;
            for(j=0;j<times;j++)
            for(k=0;k<times-j;k++)
            {
                if(j==0)temper=2;
                else temper=3;
                if(times*selecter-mines==j*3+k*2+temper)
                {
                    flag=1;
                    if(temper==2)
                    {
                    temp3=0;
                    temp2=k+1;
                    }
                    if(temper==3)
                    {
                    temp3=j+1;
                    temp2=k;
                    }
                }
            }
            if(mines==selecter*times-1)
            {
                for(j=0;j<selecter;j++)
                for(k=0;k<times;k++)
                {
                    paint[j][k]='*';
                }
                paint[0][0]='c';
            }
            else if(flag==0&&mines!=1||(selecter*times-2==mines))
            {
                fout<<"Impossible"<<endl;
                continue;
            }

            else if(flag==1)
            {
                for(j=0;j<temp3;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                }
                for(j=temp3;j<temp3+temp2;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='*';
                }
                for(j=temp3+temp2;j<times;j++)
                {
                    paint[j][0]='*';
                    paint[j][1]='*';
                    paint[j][2]='*';
                }
                paint[0][0]='c';

            }
            else if(mines==1)
            {
                for(j=0;j<times;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                }
                paint[0][0]='c';
                paint[times-1][2]='*';
            }
                if(mode==2)
                {
                for(j=0;j<selecter;j++)
                {
                    for(k=0;k<times;k++)
                    {
                        fout<<paint[k][j];
                    }
                    fout<<endl;
                }
                }
                if(mode==1)
                {
                for(j=0;j<times;j++)
                {
                    for(k=0;k<selecter;k++)
                    {
                        fout<<paint[j][k];
                    }
                    fout<<endl;
                }
                }
        }
        if(selecter==4)
        {
            flag=0;
            for(j=0;j<times;j++)
            for(k=0;k<times-j;k++)
            for(l=0;l<times-j-k;l++)
            {
                if(j==0&&k==0)temper=2;
                if(j==0&&k!=0)temper=3;
                if(j!=0)temper=4;
                if(times*selecter-mines==j*4+k*3+l*2+temper)
                {
                    flag=1;
                    if(temper==2)
                    {
                    temp4=0;
                    temp3=0;
                    temp2=l+1;
                    }
                    if(temper==3)
                    {
                    temp4=0;
                    temp3=k+1;
                    temp2=l;
                    }
                    if(temper==4)
                    {
                    temp4=j+1;
                    temp3=k;
                    temp2=l;
                    }
                }
            }
            if(mines==selecter*times-1)
            {
                for(j=0;j<selecter;j++)
                for(k=0;k<times;k++)
                {
                    paint[j][k]='*';
                }
                paint[0][0]='c';
            }
            else if(flag==0&&mines!=1||(selecter*times-2==mines))
            {
                fout<<"Impossible"<<endl;
                continue;
            }

            else if(flag==1)
            {
                for(j=0;j<temp4;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                    paint[j][3]='.';
                }
                for(j=temp4;j<temp3+temp4;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                    paint[j][3]='*';
                }
                for(j=temp3+temp4;j<temp2+temp3+temp4;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='*';
                    paint[j][3]='*';
                }
                for(j=temp3+temp2+temp4;j<times;j++)
                {
                    paint[j][0]='*';
                    paint[j][1]='*';
                    paint[j][2]='*';
                    paint[j][3]='*';
                }
                paint[0][0]='c';

            }
            else if(mines==1)
            {
                for(j=0;j<times;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                    paint[j][3]='.';
                }
                paint[0][0]='c';
                paint[times-1][3]='*';
            }
            if(mode==2)
                {
                for(j=0;j<selecter;j++)
                {
                    for(k=0;k<times;k++)
                    {
                        fout<<paint[k][j];
                    }
                    fout<<endl;
                }
                }
                if(mode==1)
                {
                for(j=0;j<times;j++)
                {
                    for(k=0;k<selecter;k++)
                    {
                        fout<<paint[j][k];
                    }
                    fout<<endl;
                }
                }
        }
        if(selecter==5)
        {
            flag=0;
            for(j=0;j<times;j++)
            for(k=0;k<times-j;k++)
            for(l=0;l<times-j-k;l++)
            for(m=0;m<times-j-k-l;m++)
            {

                if(j==0&&k==0&&l==0)temper=2;
                if(j==0&&k==0&&l!=0)temper=3;
                if(j==0&&k!=0)temper=4;
                if(j!=0)temper=5;
                if(times*selecter-mines==j*5+k*4+l*3+m*2+temper)
                {
                    flag=1;
                    if(temper==2)
                    {
                    temp5=0;
                    temp4=0;
                    temp3=0;
                    temp2=m+1;
                    }
                    if(temper==3)
                    {
                    temp5=0;
                    temp4=0;
                    temp3=l+1;
                    temp2=m;
                    }
                    if(temper==4)
                    {
                    temp5=0;
                    temp4=k+1;
                    temp3=l;
                    temp2=m;
                    }
                    if(temper==5)
                    {
                    temp5=j+1;
                    temp4=k;
                    temp3=l;
                    temp2=m;
                    }
                }
            }
            if(mines==selecter*times-1)
            {
                for(j=0;j<selecter;j++)
                for(k=0;k<times;k++)
                {
                    paint[j][k]='*';
                }
                paint[0][0]='c';
            }
            else if(flag==0&&mines!=1||(selecter*times-2==mines))
            {
                fout<<"Impossible"<<endl;
                continue;
            }

            else if(flag==1)
            {
                for(j=0;j<temp5;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                    paint[j][3]='.';
                    paint[j][4]='.';
                }
                for(j=temp5;j<temp5+temp4;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                    paint[j][3]='.';
                    paint[j][4]='*';
                }
                for(j=temp5+temp4;j<temp5+temp3+temp4;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                    paint[j][3]='*';
                    paint[j][4]='*';
                }
                for(j=temp3+temp5+temp4;j<temp3+temp5+temp4+temp2;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='*';
                    paint[j][3]='*';
                    paint[j][4]='*';
                }
                for(j=temp3+temp5+temp4+temp2;j<times;j++)
                {
                    paint[j][0]='*';
                    paint[j][1]='*';
                    paint[j][2]='*';
                    paint[j][3]='*';
                    paint[j][4]='*';
                }
                paint[0][0]='c';

            }
            else if(mines==1)
            {
                for(j=0;j<times;j++)
                {
                    paint[j][0]='.';
                    paint[j][1]='.';
                    paint[j][2]='.';
                    paint[j][3]='.';
                    paint[j][3]='.';
                }
                paint[0][0]='c';
                paint[times-1][4]='*';
            }
            if(mode==2)
                {
                for(j=0;j<selecter;j++)
                {
                    for(k=0;k<times;k++)
                    {
                        fout<<paint[k][j];
                    }
                    fout<<endl;
                }
                }
                if(mode==1)
                {
                for(j=0;j<times;j++)
                {
                    for(k=0;k<selecter;k++)
                    {
                        fout<<paint[j][k];
                    }
                    fout<<endl;
                }
                }
        }


    }
return 0;
}
