// {{{ Boilerplate Code <--------------------------------------------------
// vim:filetype=cpp:foldmethod=marker:foldmarker={{{,}}}

#include <algorithm>
#include <bitset>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>
#include <iostream>
#include <list>
#include <map>
#include <numeric>
#include <queue>
#include <set>
#include <sstream>
#include <stack>
#include <utility>
#include <vector>

#define FOR(I,A,B) for(int I = (A); I < (B); ++I)
#define ALL(A)     (A).begin(), (A).end()

using namespace std;

// }}}

int main(){
	int ans[10000];
	FOR(i,0,10000)
		ans[i]=-1;

	// ans list was generated by c_search.cpp

	ans[650]=0;
	ans[675]=0;
	ans[676]=26;
	ans[700]=0;
	ans[701]=27;
	ans[702]=77;
	ans[725]=0;
	ans[726]=27;
	ans[727]=78;
	ans[728]=178;
	ans[750]=0;
	ans[751]=27;
	ans[752]=78;
	ans[753]=179;
	ans[754]=379;
	ans[1275]=0;
	ans[1276]=30;
	ans[1300]=0;
	ans[1303]=181;
	ans[1325]=0;
	ans[1327]=227;
	ans[1330]=782;
	ans[1350]=0;
	ans[1352]=427;
	ans[1354]=1278;
	ans[1357]=3183;
	ans[1375]=0;
	ans[1377]=827;
	ans[1379]=2478;
	ans[1381]=5779;
	ans[1384]=12784;
	ans[1900]=0;
	ans[1901]=35;
	ans[1902]=85;
	ans[1925]=0;
	ans[1927]=85;
	ans[1930]=786;
	ans[1950]=0;
	ans[1951]=27;
	ans[1953]=185;
	ans[1955]=1987;
	ans[1958]=6387;
	ans[1975]=0;
	ans[1976]=27;
	ans[1977]=78;
	ans[1979]=385;
	ans[1978]=6827;
	ans[1981]=7187;
	ans[1983]=20788;
	ans[1986]=51188;
	ans[2000]=0;
	ans[2001]=27;
	ans[2002]=78;
	ans[2003]=179;
	ans[2005]=785;
	ans[2004]=26478;
	ans[2007]=27187;
	ans[2006]=79278;
	ans[2009]=79988;
	ans[2011]=185589;
	ans[2014]=409589;
	ans[2525]=0;
	ans[2526]=35;
	ans[2527]=90;
	ans[2528]=190;
	ans[2550]=0;
	ans[2552]=85;
	ans[2554]=390;
	ans[2557]=3191;
	ans[2575]=0;
	ans[2576]=27;
	ans[2578]=185;
	ans[2577]=227;
	ans[2579]=387;
	ans[2581]=1590;
	ans[2583]=15992;
	ans[2586]=51192;
	ans[2600]=0;
	ans[2601]=27;
	ans[2602]=78;
	ans[2604]=385;
	ans[2603]=478;
	ans[2605]=787;
	ans[2606]=1588;
	ans[2608]=6390;
	ans[2607]=109587;
	ans[2610]=115192;
	ans[2612]=332793;
	ans[2615]=819193;
	ans[2625]=0;
	ans[2626]=27;
	ans[2627]=78;
	ans[2628]=179;
	ans[2630]=785;
	ans[2629]=979;
	ans[2631]=1587;
	ans[2632]=3188;
	ans[2633]=6389;
	ans[2635]=25590;
	ans[2634]=847988;
	ans[2637]=870392;
	ans[2636]=2537588;
	ans[2639]=2559993;
	ans[2641]=5939194;
	ans[2644]=13107194;
	ans[3150]=0;
	ans[3151]=35;
	ans[3152]=90;
	ans[3153]=195;
	ans[3154]=395;
	ans[3175]=0;
	ans[3177]=85;
	ans[3179]=390;
	ans[3181]=1595;
	ans[3184]=12796;
	ans[3200]=0;
	ans[3201]=27;
	ans[3203]=185;
	ans[3202]=227;
	ans[3204]=387;
	ans[3206]=1590;
	ans[3205]=1987;
	ans[3207]=3192;
	ans[3209]=12795;
	ans[3211]=127997;
	ans[3214]=409597;
	ans[3225]=0;
	ans[3226]=27;
	ans[3227]=78;
	ans[3229]=385;
	ans[3228]=478;
	ans[3230]=787;
	ans[3231]=1588;
	ans[3233]=6390;
	ans[3232]=7988;
	ans[3234]=12792;
	ans[3235]=25593;
	ans[3237]=102395;
	ans[3236]=1753592;
	ans[3239]=1843197;
	ans[3241]=5324798;
	ans[3244]=13107198;
	ans[3250]=0;
	ans[3251]=27;
	ans[3252]=78;
	ans[3253]=179;
	ans[3255]=785;
	ans[3254]=979;
	ans[3256]=1587;
	ans[3257]=3188;
	ans[3258]=6389;
	ans[3260]=25590;
	ans[3259]=31989;
	ans[3261]=51192;
	ans[3262]=102393;
	ans[3263]=204794;
	ans[3265]=819195;
	ans[3264]=27135993;
	ans[3267]=27852797;
	ans[3266]=81203193;
	ans[3269]=81919998;
	ans[3271]=190054399;
	ans[3274]=419430399;

	int T;

	cin>>T;



	FOR(iteration,0,T){
		cout<<"Case #"<<(iteration+1)<<": \n";
		int r,c,m;

		cin>>r>>c>>m;

		int a=ans[r*625+c*25+m];

		if(a==-1){
			cout<<"Impossible\n";
		}else{
			int maps=a/25;
			int i=(a%25)/5;
			int j=a%5;

			FOR(k,0,r){
				FOR(l,0,c){
					if(((maps>>(k*c+l))&1)==1)
						cout<<'*';
					else
						if(k==i && l==j)
							cout<<'c';
						else
							cout<<'.';


				}
				cout<<'\n';
			}

		}
	}
}
