#include<stdio.h>
char a[50][50];
main()
{
	freopen("read2.in","r",stdin);
	freopen("write2.out","w",stdout);
	int t,cs,n,m,i,j,k;
	char temp;
	scanf("%d",&t);
	for(cs=1;cs<=t;cs++)
	{
		scanf("%d",&n);
		int x[26]={0};
		scanf("%d",&m);
		for(i=0;i<n;i++)
		{
			scanf("%s",&a[i]);
		}
		for(i=0;i<n;i++)
		{
			j=0;
			while(j<m)
			{
				if((a[i][j]!='?')&&(x[a[i][j]-65]==0))
				{
					temp=a[i][j];
					int check=0;
					j++;
					while((a[i][j]=='?')&&(j<m))
					{
						a[i][j]=temp;
						j++;
						check=1;
					}
					//x[temp-65]=1;
					if(check==1)
					j--;
				}
				//printf("%d\n",j);
				j++;
			}
			for(j=0;j<m;j++)
			{
				if((a[i][j]!='?')&&(x[a[i][j]-65]==0))
				{
					temp=a[i][j];
					break;
				}
			}
			if(j<m)
			{
				for(j;j>=0;j--)
					a[i][j]=temp;
			}
			if(j==m)
			{
				if(i>0)
				{
					for(j=0;j<m;j++)
					{
						a[i][j]=a[i-1][j];
					}
				}
			}
			for(j=0;j<m;j++)
			{
				if(a[i][j]!='?')
					x[a[i][j]-65]=1;
			}
		}
		for(i=0;i<n;i++)
		{
			if(a[i][0]!='?')
				break;
		}
		if(i>0)
		{
			for(i=i-1;i>=0;i--)
			{
				for(j=0;j<m;j++)
				{
					a[i][j]=a[i+1][j];
				}
			}
		}
		printf("Case #%d:\n",cs);
		for(i=0;i<n;i++)
		{
			for(j=0;j<m;j++)
			{
				if(a[i][j]=='?')
					a[i][j]=a[i][j-1];
				printf("%c",a[i][j]);
			}
			printf("\n");
		}
	}
}
