#include<cstdio>
int v[7],i,j,n,m,k,t,vc[1001],poz;
char s[]={0,'R','O','Y','G','B','V'};
int main ()
{
freopen("date.in","r",stdin);
freopen("date.out","w",stdout);
scanf("%d",&t);
for(int co=1;co<=t;co++)
    {
    scanf("%d",&n);
    poz=1;
    for(i=1;i<=6;i++)
        scanf("%d",&v[i]);
    for(i=1;i<=n;i++)
        vc[i]=0;
    if(v[2]!=0)
        {
        while(v[2]!=0)
            {
            vc[poz]=5;
            vc[poz+1]=2;
            v[2]--;
            v[5]--;
            poz+=2;
            }
        if(poz<n)
            {
            vc[poz]=5;
            v[5]--;
            poz++;
            }
        }
    if(v[4]!=0)
        {
        while(v[4]!=0)
            {
            vc[poz]=1;
            vc[poz+1]=4;
            v[4]--;
            v[1]--;
            poz+=2;
            }
        if(poz<n)
            {
            vc[poz]=1;
            v[1]--;
            poz++;
            }
        }
    if(v[6]!=0)
        {
        while(v[6]!=0)
            {
            vc[poz]=3;
            vc[poz+1]=6;
            v[6]--;
            v[3]--;
            poz+=2;
            }
        if(poz<n)
            {
            vc[poz]=3;
            v[3]--;
            poz++;
            }
        }
    int x=v[poz-1];
    while(v[1]!=0||v[3]!=0||v[5]!=0)
        {
        int maxim=0,poz2;
        for(i=1;i<=5;i+=2)
            if(x!=i&&v[i]>maxim)
                {
                poz2=i;
                maxim=v[i];
                }
        if(maxim==0)
            break;
        else
            {
            vc[poz]=poz2;
            v[poz2]--;
            x=poz2;
            poz++;
            }
        }
    int pp=0;
    poz--;
    if(poz==n&&vc[n]==vc[1])
        {
        int aux;
        pp=2;
        if(vc[3]!=vc[1])
            {
            aux=vc[2];
            vc[2]=vc[1];
            vc[1]=aux;
            pp=1;
            }
        if(vc[n]!=vc[n-2])
            {
            aux=vc[n-1];
            vc[n-1]=vc[n];
            vc[n]=aux;
            pp=1;
            }
        for(i=2;i<=n-1&&pp==2;i++)
            if(vc[i]!=vc[n]&&vc[n]!=vc[i-1]&&vc[n]!=vc[i+1])
                {
                aux=vc[i];
                vc[i]=vc[n];
                vc[n]=aux;
                pp=1;
                break;
                }
        }
    for(i=1;i<=6;i++)
        if(v[i]!=0)
            pp=2;
    printf("Case #%d: ",co);
    if(pp==2||poz!=n)
        printf("IMPOSSIBLE\n");
    else
        {
        for(i=1;i<=n;i++)
            printf("%c",s[vc[i]]);
        printf("\n");
        }
    }
return 0;
}
