{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": true,
    "editable": true
   },
   "source": [
    "# Google Code Jam 2017 — Round 2 — problem A\n",
    "## User: jdemeyer\n",
    "\n",
    "This is a Jupyter notebook to be run with SageMath version 8.0.beta6 on a 64-bit GNU/Linux system. Although the precise version of SageMath probably does not matter that much."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "%%cython\n",
    "\n",
    "include \"signals.pxi\"\n",
    "\n",
    "import os, sys, datetime, time\n",
    "from sage.rings.integer cimport Integer\n",
    "import numpy as np\n",
    "\n",
    "\n",
    "def log(msg):\n",
    "    sys.stderr.write(msg + \"\\n\")\n",
    "    sys.stderr.flush()\n",
    "\n",
    "\n",
    "class CodejamProblem(object):\n",
    "    def __init__(self, input):\n",
    "        self.inputlines = iter(input.splitlines())\n",
    "        self.cases = []\n",
    "    \n",
    "    def readline(self):\n",
    "        return next(self.inputlines)\n",
    "        \n",
    "    def readint(self):\n",
    "        return Integer(self.readline())\n",
    "\n",
    "    def readints(self):\n",
    "        return [Integer(x) for x in self.readline().split()]\n",
    "        \n",
    "    def solve(self, f=sys.stdout, raw=False):\n",
    "        for i, case in enumerate(self.cases, 1):\n",
    "            sig_check()\n",
    "            ans = self.solvecase(case)\n",
    "            if raw:\n",
    "                ans = repr(ans)\n",
    "            else:\n",
    "                ans = self.formatanswer(ans)\n",
    "            f.write(\"Case #{0}: {1}\\n\".format(i, ans))\n",
    "        f.flush()\n",
    "        \n",
    "    def solvecheck(self, output):\n",
    "        from StringIO import StringIO\n",
    "        out = StringIO()\n",
    "        self.solve(out)\n",
    "        assert out.getvalue() == output\n",
    "            \n",
    "    def formatanswer(self, ans):\n",
    "        return str(ans)\n",
    "\n",
    "    @classmethod\n",
    "    def precompute(cls):\n",
    "        pass\n",
    "    \n",
    "    @classmethod\n",
    "    def autosolve(cls, filein, fileout, *args, **kwds):\n",
    "        log(\"precomputing...\")\n",
    "        cls.precompute()\n",
    "\n",
    "        log(\"autosolving...\")\n",
    "\n",
    "        nexc = 0\n",
    "        while nexc < 10:\n",
    "            sig_check()\n",
    "            t0 = datetime.datetime.now()\n",
    "            try:\n",
    "                input = open(filein).read()\n",
    "            except IOError:\n",
    "                time.sleep(0.2)\n",
    "                continue\n",
    "            d = datetime.datetime.now() - t0\n",
    "            log(\"Read input in %.2fs\" % d.total_seconds())\n",
    "            \n",
    "            t0 = datetime.datetime.now()\n",
    "            try:\n",
    "                problem = cls(input, *args, **kwds)\n",
    "            except Exception:\n",
    "                from traceback import print_exc\n",
    "                print_exc(file=sys.stderr)\n",
    "                nexc += 1\n",
    "                time.sleep(0.5)\n",
    "                continue\n",
    "            d = datetime.datetime.now() - t0\n",
    "            ncases = len(problem.cases)\n",
    "            log(\"Parsed input in %.2fs, got %s cases\" % (d.total_seconds(), ncases))\n",
    "            \n",
    "            t0 = datetime.datetime.now()\n",
    "            with open(fileout, 'w') as out:\n",
    "                problem.solve(out)\n",
    "            d = datetime.datetime.now() - t0\n",
    "            log(\"Solved problem in %.2fs\" % d.total_seconds())\n",
    "\n",
    "            problem.notify()\n",
    "            return\n",
    "        \n",
    "    @staticmethod\n",
    "    def notify():\n",
    "        os.system(\"mplayer /usr/share/apps/kgoldrunner/themes/default/victory.ogg >/dev/null\")\n",
    "    \n",
    "\n",
    "class Problem(CodejamProblem):\n",
    "    def __init__(self, input):\n",
    "        CodejamProblem.__init__(self, input)\n",
    "        \n",
    "        T = self.readint()\n",
    "        for i in range(T):\n",
    "            N, P = self.readints()\n",
    "            G = self.readints()\n",
    "            self.cases.append((P,G))\n",
    "        \n",
    "    def solvecase(self, case):\n",
    "        P, G = case\n",
    "        NG = [0] * P\n",
    "        for g in G:\n",
    "            NG[g % P] += 1\n",
    "        assert sum(NG) == len(G)\n",
    "        \n",
    "        w = sum(i*NG[i] for i in range(P))\n",
    "        \n",
    "        good = 1\n",
    "        while True:            \n",
    "            for i in range(P):\n",
    "                assert NG[i] >= 0\n",
    "                \n",
    "            wnew = sum(i*NG[i] for i in range(P))\n",
    "            assert (w - wnew) % P == 0\n",
    "            \n",
    "            SNG = sum(NG)\n",
    "            if SNG <= 1:\n",
    "                assert(SNG == 1)\n",
    "                break\n",
    "                \n",
    "            if NG[0] >= 1:\n",
    "                NG[0] -= 1\n",
    "                good += 1\n",
    "            elif P == 2:\n",
    "                if SNG > 2 and NG[1] >= 2:\n",
    "                    NG[1] -= 2\n",
    "                    good += 1\n",
    "                else:\n",
    "                    break\n",
    "            elif P == 3:\n",
    "                if SNG > 2 and NG[1] >= 1 and NG[2] >= 1:\n",
    "                    NG[1] -= 1\n",
    "                    NG[2] -= 1\n",
    "                    good += 1\n",
    "                elif SNG > 3 and NG[1] >= 3:\n",
    "                    NG[1] -= 3\n",
    "                    good += 1\n",
    "                elif SNG > 3 and NG[2] >= 3:\n",
    "                    NG[2] -= 3\n",
    "                    good += 1\n",
    "                else:\n",
    "                    break\n",
    "            elif P == 4:\n",
    "                if SNG > 2 and NG[1] >= 1 and NG[3] >= 1:\n",
    "                    NG[1] -= 1\n",
    "                    NG[3] -= 1\n",
    "                    good += 1\n",
    "                elif SNG > 2 and NG[2] >= 2:\n",
    "                    NG[2] -= 2\n",
    "                    good += 1\n",
    "                elif SNG > 3 and NG[1] >= 2 and NG[2] >= 1:\n",
    "                    NG[1] -= 2\n",
    "                    NG[2] -= 1\n",
    "                    good += 1\n",
    "                elif SNG > 3 and NG[3] >= 2 and NG[2] >= 1:\n",
    "                    NG[3] -= 2\n",
    "                    NG[2] -= 1\n",
    "                    good += 1\n",
    "                elif SNG > 4 and NG[1] >= 4:\n",
    "                    NG[1] -= 4\n",
    "                    good += 1\n",
    "                elif SNG > 4 and NG[3] >= 4:\n",
    "                    NG[3] -= 4\n",
    "                    good += 1\n",
    "                else:\n",
    "                    break\n",
    "        return good"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "input=\"\"\"\n",
    "8\n",
    "4 3\n",
    "4 5 6 4\n",
    "4 2\n",
    "4 5 6 4\n",
    "3 3\n",
    "1 1 1\n",
    "4 4\n",
    "4 5 6 4\n",
    "8 4\n",
    "1 1 1 1 3 3 3 3\n",
    "8 4\n",
    "1 1 1 1 2 2 2 2\n",
    "8 4\n",
    "2 2 2 2 3 3 3 3\n",
    "8 4\n",
    "1 1 1 3 3 3 2 2\n",
    "\"\"\"\n",
    "\n",
    "output=\"\"\"\n",
    "Case #1: 3\n",
    "Case #2: 4\n",
    "Case #3: 1\n",
    "Case #4: 3\n",
    "Case #5: 4\n",
    "Case #6: 3\n",
    "Case #7: 3\n",
    "Case #8: 4\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "input = \"\".join(line+\"\\n\" for line in input.splitlines() if line)\n",
    "output = \"\".join(line+\"\\n\" for line in output.splitlines() if line)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": [
    "P = Problem(input)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Case #1: 3\n",
      "Case #2: 4\n",
      "Case #3: 1\n",
      "Case #4: 3\n",
      "Case #5: 4\n",
      "Case #6: 3\n",
      "Case #7: 3\n",
      "Case #8: 4\n"
     ]
    }
   ],
   "source": [
    "P.solve(raw=True)\n",
    "P.solvecheck(output)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {
    "collapsed": false,
    "deletable": true,
    "editable": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "precomputing...\n",
      "autosolving...\n",
      "Read input in 0.00s\n",
      "Parsed input in 0.00s, got 75 cases\n",
      "Solved problem in 0.06s\n"
     ]
    }
   ],
   "source": [
    "P.autosolve(\"in/A-small-attempt0.in\", \"out\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true,
    "deletable": true,
    "editable": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "SageMath 8.0.beta4",
   "language": "",
   "name": "sagemath"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
