f=open("abc.txt")
n=f.readline()
n=int(n)
for i in range(1,n+1):
    le=0
    j=0
    z=0
    st=f.readline()
    le=len(st)
    st=list(st)
    for j in range(le):
            if(st[j]=='a'):
                st[j]=st[j].replace('a','y')
                continue
            if(st[j]=='b'):
                st[j]=st[j].replace('b','h')
                continue
            if(st[j]=='c'):
                st[j]=st[j].replace('c','e')
                continue
            if(st[j]=='d'):
                st[j]=st[j].replace('d','s')
                continue
            if(st[j]=='e'):
                st[j]=st[j].replace('e','o')
                continue
            if(st[j]=='f'):
                st[j]=st[j].replace('f','c')
                continue
            if(st[j]=='g'):
                st[j]=st[j].replace('g','v')
                continue
            if(st[j]=='h'):
                st[j]=st[j].replace('h','x')
                continue
            if(st[j]=='i'):
                st[j]=st[j].replace('i','d')
                continue
            if(st[j]=='j'):
                st[j]=st[j].replace('j','u')
                continue
            if(st[j]=='k'):
                st[j]=st[j].replace('k','i')
                continue
            if(st[j]=='l'):
                st[j]=st[j].replace('l','g')
                continue
            if(st[j]=='m'):
                st[j]=st[j].replace('m','l')
                continue
            if(st[j]=='n'):
                st[j]=st[j].replace('n','b')
                continue
            if(st[j]=='o'):
                st[j]=st[j].replace('o','k')
                continue
            if(st[j]=='p'):
                st[j]=st[j].replace('p','r')
                continue
            if(st[j]=='q'):
                st[j]=st[j].replace('q','z')
                continue
            if(st[j]=='r'):
                st[j]=st[j].replace('r','t')
                continue
            if(st[j]=='s'):
                st[j]=st[j].replace('s','n')
                continue
            if(st[j]=='t'):
                st[j]=st[j].replace('t','w')
                continue
            if(st[j]=='u'):
                st[j]=st[j].replace('u','j')
                continue
            if(st[j]=='v'):
                st[j]=st[j].replace('v','p')
                continue
            if(st[j]=='w'):
                st[j]=st[j].replace('w','f')
                continue
            if(st[j]=='x'):
                st[j]=st[j].replace('x','m')
                continue
            if(st[j]=='y'):
                st[j]=st[j].replace('y','a')
                continue
            if(st[j]=='z'):
                st[j]=st[j].replace('z','q')
                continue
    print("Case #"+str(i)+": ",end='')
    for z in range(le):
        print(st[z],end='')
