#include <fstream>
#include <iomanip>
#include <iostream>
using namespace std;

// Problem B. Cookie Clicker Alpha

const double start_rate = 2.0;
double C;	// cost of cookie farm
double F;	// extra cookies generated by farm
double X;	// winning condition

double time_till_X (double rate) {
	return X / rate;
}

int main () {
	//string infile = "sample.txt";
	//string infile = "B-small-attempt0.in";
	string infile = "B-large.in";
	string outfile = "output.txt";

	ifstream in(infile);
	ofstream out(outfile);

	int T;
	in >> T;
	for (int i = 1; i <= T; ++i) {
		double rate = start_rate;
		double best_time;

		out << "Case #" << i << ": ";
		in >> C >> F >> X;
		best_time = time_till_X(rate);
		
		double part_time = 0;
		out << setprecision(7) << fixed;
		while (true) {
			part_time += C/rate;
			rate += F;
			double total_time = part_time + time_till_X(rate);
			if (total_time < best_time) {
				best_time = total_time;
			} else {
				out << best_time << endl;
				break;
			}
		}
	}

	return 0;
}
