#include <iostream>
#include <vector>

using namespace std;

// vector generated by following code in Haskell: 
// [ x | y <- [1..10000000], reverse (show y) == show y, let x = y*y, reverse (show x) == show x]

vector<long long> palls = {1,4,9,121,484,10201,12321,14641,40804,44944,1002001,1234321,4008004,100020001,102030201,104060401,121242121,123454321,125686521,400080004,404090404,10000200001,10221412201,12102420121,12345654321,40000800004,1000002000001,1002003002001,1004006004001,1020304030201,1022325232201,1024348434201,1210024200121,1212225222121,1214428244121,1232346432321,1234567654321,4000008000004,4004009004004};

int main(){
    int T;
    cin >> T;
    for(int t = 1; t<=T; ++t){
        cout << "Case #" << t << ": ";
        int A, B;
        cin >> A >> B;
        unsigned lower = 0, upper = palls.size()-1;
        while(lower < palls.size() && palls[lower] < A) lower++;
        while(upper >= 0 && palls[upper] > B) upper--;
        cout << upper + 1 - lower << '\n';
    }
    return 0;
}
