#include<iostream.h>
#include<math.h>
#include<stdio.h>
void main()
{       int i,j,sq2,T,N,temp1,count=0;
	double sq,temp,A,B;
	freopen("C1.in","r",stdin);
	freopen("C1.out","w",stdout);
	cin>>T;
	for(i=1;i<=T;i++)
	{
		cin>>A>>B;
		if(A<=B)
		{
			for(j=A;j<=B;j++)
			{
				sq=sqrt(j);
				sq2=fabs(sq);
				if(sq2==sq)
				{
					temp=0;
					N=0;
					while(sq2>0)
					{
						temp1=sq2%10;
						sq2=sq2/10;
						temp=temp*10+temp1;
					}
					if(temp==sqrt(j))
					{
						N++;
					}
					temp=0;
					sq2=j;
					while(sq2>0)
					{
						temp1=sq2%10;
						sq2=sq2/10;
						temp=temp*10+temp1;
					}
					if(temp==j)
						N++;
					if(N==2)
						count++;
				}
			}
		}
		cout<<"Case #"<<i<<": "<<count<<"\n";
		count=0;
	}
}