/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author HSK
 */

#include <iostream>
#include <fstream>

#include <bits/stdc++.h>
using namespace std;

class TaskA {
 public:
  void solve(std::istream &in, std::ostream &out) {
    int T;
    in >> T;

    for (int t = 1; t <= T; t++) {
      string S;
      int K;
      in >> S >> K;

      int len = (int)S.length() - K + 1;
      int ans = 0;

      for (int i = 0; i < len; i++) {
        if (S[i] == '-') {
          for (int j = i; j < i + K; j++) {
            S[j] = (S[j] == '+') ? '-' : '+';
          }

          ans++;
        }
      }

      bool is_impossible = false;

      for (int i = len; i < S.length(); i++) {
        if (S[i] == '-') {
          is_impossible = true;
          break;
        }
      }

      out << "Case #" << t << ": ";
      if (is_impossible) {
        out << "IMPOSSIBLE\n";
      } else {
        out << ans << "\n";
      }
    }
  }
};

#include <dirent.h>
#include <stdexcept>
#include <regex>
#include <sys/stat.h>
#include <cstdint>

std::string getLastFileName(const std::string& regexString) {
	DIR* dir;
	dirent* entry;
	std::string result = "";
	int64_t resultModificationTime = 0;
	std::regex regex(regexString);
	if ((dir = opendir (".")) != NULL) {
		while ((entry = readdir (dir)) != NULL) {
			if (std::regex_match(entry->d_name, regex)) {
				struct stat buffer;
				stat(entry->d_name, &buffer);
				int64_t modificationTime = static_cast<int64_t>(buffer.st_mtimespec.tv_sec) * 1000000000 +
						static_cast<int64_t>(buffer.st_mtimespec.tv_nsec);

				if (modificationTime > resultModificationTime) {
					resultModificationTime = modificationTime;
					result = entry->d_name;
				}
			}
		}
		closedir (dir);
	} else {
		throw std::runtime_error("Couldn't open current directory");
	}
	if (result.empty()) {
		throw std::runtime_error("No file found");
	}	return result;
}

int main() {
	TaskA solver;
	std::ifstream in(getLastFileName("A-(small|large).*[.]in"));
	std::ofstream out("a.out");
	solver.solve(in, out);
	return 0;
}
