{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def digits(s):\n",
    "    ans = []\n",
    "    list_s = list(s)\n",
    "    digits = [\"ZERO\", \"ONE\", \"TWO\", \"THREE\", \"FOUR\", \"FIVE\", \"SIX\", \"SEVEN\", \"EIGHT\", \"NINE\"]\n",
    "    zeros = s.count('Z')\n",
    "    ans.extend([0] * zeros)\n",
    "    while zeros:\n",
    "        list_s.remove('Z')\n",
    "        list_s.remove('E')\n",
    "        list_s.remove('R')\n",
    "        list_s.remove('O')\n",
    "        zeros -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    twos = s.count('W')\n",
    "    ans.extend([2] * twos)\n",
    "    while twos:\n",
    "        list_s.remove('T')\n",
    "        list_s.remove('W')\n",
    "        list_s.remove('O')\n",
    "        twos -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    fours = s.count('U')\n",
    "    ans.extend([4] * fours)\n",
    "    while fours:\n",
    "        list_s.remove('F')\n",
    "        list_s.remove('O')\n",
    "        list_s.remove('U')\n",
    "        list_s.remove('R')\n",
    "        fours -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    fives = s.count('F')\n",
    "    ans.extend([5] * fives)\n",
    "    while fives:\n",
    "        list_s.remove('F')\n",
    "        list_s.remove('I')\n",
    "        list_s.remove('V')\n",
    "        list_s.remove('E')\n",
    "        fives -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    sixes = s.count('X')\n",
    "    ans.extend([6] * sixes)\n",
    "    while sixes:\n",
    "        list_s.remove('S')\n",
    "        list_s.remove('I')\n",
    "        list_s.remove('X')\n",
    "        sixes -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    eights = s.count('G')\n",
    "    ans.extend([8] * eights)\n",
    "    while eights:\n",
    "        list_s.remove('E')\n",
    "        list_s.remove('I')\n",
    "        list_s.remove('G')\n",
    "        list_s.remove('H')\n",
    "        list_s.remove('T')\n",
    "        eights -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    threes = s.count('H')\n",
    "    ans.extend([3] * threes)\n",
    "    while eights:\n",
    "        list_s.remove('T')\n",
    "        list_s.remove('H')\n",
    "        list_s.remove('R')\n",
    "        list_s.remove('E')\n",
    "        list_s.remove('E')\n",
    "        threes -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    ones = s.count('O')\n",
    "    ans.extend([1] * ones)\n",
    "    while ones:\n",
    "        list_s.remove('O')\n",
    "        list_s.remove('N')\n",
    "        list_s.remove('E')\n",
    "        ones -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    sevens = s.count('S')\n",
    "    ans.extend([7] * sevens)\n",
    "    while ones:\n",
    "        list_s.remove('S')\n",
    "        list_s.remove('E')\n",
    "        list_s.remove('V')\n",
    "        list_s.remove('E')\n",
    "        list_s.remove('N')\n",
    "        sevens -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    nines = s.count('I')\n",
    "    ans.extend([9] * nines)\n",
    "    while ones:\n",
    "        list_s.remove('N')\n",
    "        list_s.remove('I')\n",
    "        list_s.remove('N')\n",
    "        list_s.remove('E')\n",
    "        nines -= 1\n",
    "    s = ''.join(list_s)\n",
    "    list_s = list(s)\n",
    "    \n",
    "    ans.sort()\n",
    "    \n",
    "    return ''.join([str(_) for _ in ans])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'24679'"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "digits('NUFTOSREENXOISVWINE')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "OZONETOWER 012\n",
      "WEIGHFOXTOURIST 2468\n",
      "OURNEONFOE 114\n",
      "ETHER 3\n",
      "NEVSEHEREZEOTR 037\n",
      "NOZOERNWEEOTO 0112\n",
      "NNENIEINEIENINIENNNN 99999\n",
      "SNIENIXOSOXE 1166\n",
      "OHTETXWWEORITS 2236\n",
      "NEENOEONOIENEONN 11119\n",
      "NVHSEEEORETEN 137\n",
      "WIIONENNNET 299\n",
      "OGNOFUHERTEI 148\n",
      "OSIXTW 26\n",
      "RUFO 4\n",
      "ZWROETO 02\n",
      "EEOZONR 01\n",
      "ETVEEENHRS 37\n",
      "EUREISFOISFVEXNV 4567\n",
      "HFENEEIRTOVE 135\n",
      "NOE 1\n",
      "ZOER 0\n",
      "TTWWOWOEOTNTOOWTOW 122222\n",
      "EGENWTNITOIH 289\n",
      "GTTHEREEIH 38\n",
      "EROUFRHEZEOTR 034\n",
      "VNENNONENVEIEESSE 1779\n",
      "NEVNNIFXEIVIESSE 5679\n",
      "EENNNINNENNOIINEEO 11999\n",
      "RFUO 4\n",
      "IUVVNEEVOFENERESSF 4577\n",
      "IIENIOHGNEEFTRNNU 4899\n",
      "NVVNNESEEEFONEII 1579\n",
      "INENINNINNENINEOEEN 19999\n",
      "EHGTI 8\n",
      "EEFFVIIV 55\n",
      "INZSOOWOETEXR 0126\n",
      "ENWNOOEENEOOOONNET 111112\n",
      "OEN 1\n",
      "OENEINXINNESO 1169\n",
      "NEENENNEOEOOONO 11111\n",
      "OUZERFEEOVNSR 047\n",
      "THWRTOEE 23\n",
      "NONONETENOTWOOEEOW 111122\n",
      "EVESN 7\n",
      "ENOINNEONIENONENE 11199\n",
      "UWTXUSIRRSFOXOFOI 24466\n",
      "SENEV 7\n",
      "EOORERZZ 00\n",
      "ZENISTEEGORXIVSHE 0678\n",
      "FEIOUTHRG 48\n",
      "ERZO 0\n",
      "EIFVFIVE 55\n",
      "THGEI 8\n",
      "EIVHNFIGEEOT 158\n",
      "XISIFEINVEN 569\n",
      "NEINEUGEONIOFRTH 1489\n",
      "UFIORHISXUXRTEOESRF 34466\n",
      "ENFWOTVZIREFEOIRNOU 02459\n",
      "WOOEEENEWNNOTSTEOVNO 111227\n",
      "UIOFERNN 49\n",
      "UNFEEONORNI 149\n",
      "OEFWVTI 25\n",
      "ENEREOENSSTEVVOWZ 0277\n",
      "VUEOFRIF 45\n",
      "RHTOTWEE 23\n",
      "HIGET 8\n",
      "SESXURENFIVO 467\n",
      "NNVENONOEENESIE 1179\n",
      "EONOONNOOEENNEENEO 111111\n",
      "EFETOFVOTONEOWNVIIEW 112255\n",
      "NENOOE 11\n",
      "FVEI 5\n",
      "ZRZEOEONOERZRROOEZE 00001\n",
      "ESOEONXNI 116\n",
      "VNESE 7\n",
      "NENINEO 19\n",
      "RHTEWOUEERETVOFNS 2347\n",
      "WESHTRNNTEOEEOWTIVNE 22379\n",
      "NRNEIOZEENO 019\n",
      "EIGNVEETZOEHRS 078\n",
      "EOGHIENT 18\n",
      "EIIXOSINNFSEEXVO 11566\n",
      "EIEOXRHNSRROTOUEEZF 01346\n",
      "NIEGTHETGNWTHIOIE 2889\n",
      "OTRZVIHOEEEFEZRRE 0035\n",
      "EVIIVNEEEFIXFSVS 5567\n",
      "NNFERSNEEEIVOVOEZINE 01579\n",
      "WTWEOTTEWONOOWNTOO 112222\n",
      "ENO 1\n",
      "ZENEOGEISTVERHXSI 0678\n",
      "VEEFNNISXNIVSEIE 5679\n",
      "OTWOWOTWWOTOWTTWOT 222222\n",
      "OWWNNONTEEOTTWOEOO 111222\n",
      "RZEOOOEEREZRRZRZZOEO 00000\n",
      "UOIIHNEXFGTOTSEOWR 12468\n",
      "NFENOVINNRZIEEEI 0599\n",
      "ENISOIVNEENENNEN 1799\n",
      "TUHGNEREFIHREOTOE 1348\n",
      "EOEEHNGTNVSIE 178\n"
     ]
    }
   ],
   "source": [
    "inp = open(\"A-large.in\")\n",
    "out = open(\"output.txt\", 'w')\n",
    "num = int(inp.readline())\n",
    "for i in range(num):\n",
    "    s = inp.readline().strip()\n",
    "    #print s, digits(s)\n",
    "    out.write('Case #' + str(i+1) + ': ' + digits(s) + '\\n')\n",
    "inp.close()\n",
    "out.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
