#include<stdio.h>
int main()
{
	int i,j,k,t,m,n,lawn[101][101],current[101][101],rowmax[101],colmax[101],flag,max;
	scanf("%d",&t);
	for(i=0;i<t;i++)
	{	
		flag=0;
		max=-1;
		scanf("%d%d",&m,&n);
		for(j=0;j<m;j++)
			for(k=0;k<n;k++)
			{
				scanf("%d",&lawn[j][k]);
				max=(lawn[j][k]>max)?lawn[j][k]:max;
			}
		for(j=0;j<m;j++)
		{
			for(k=0;k<n;k++)
			{
				current[j][k]=max;
			}
		}
		for(j=0;j<m;j++)
		{
			rowmax[j]=-1;
			for(k=0;k<n;k++)
			{
				rowmax[j]=(lawn[j][k]>rowmax[j])?lawn[j][k]:rowmax[j];
			}
		}
		for(k=0;k<n;k++)
		{
			colmax[k]=-1;
			for(j=0;j<m;j++)
			{
				colmax[k]=(lawn[j][k]>colmax[k])?lawn[j][k]:colmax[k];
			}
		}
		for(j=0;j<m;j++)
		{
			for(k=0;k<n;k++)
			{
				current[j][k]=(current[j][k]>rowmax[j])?rowmax[j]:current[j][k];
				current[j][k]=(current[j][k]>colmax[k])?colmax[k]:current[j][k];
				if(current[j][k]!=lawn[j][k])
				{
					flag=1;
				}
			}
		}
		printf("Case #%d: ",i+1);
		if(flag==0)
			printf("YES\n");
		else
			printf("NO\n");
	}
	return 0;
}
